### PR TITLE
nv2a: Implement texture LOD bias

### LINKED ISSUE #767: Handling of LOD bias is silently unimplemented
### Bug Description

While investigating the shimmer effect in https://github.com/mborgerson/xemu/issues/270 I noticed that Ninja Gaiden Black sets the `NV_PGRAPH_TEXFILTER0_MIPMAP_LOD_BIAS` portion of `NV_PGRAPH_TEXFILTER0` to a non-zero value in the bugged render pass. At the moment I'm not sure how much this is actually contributing to the corruption, but presumably it at least has some effect that will make the rendering incorrect.

### Expected Behavior

Handling should be implemented to match hardware behavior.

I'm not sure if it's safe to assume that the nv2a LOD bias range matches the OpenGL range, but if it does maybe we can just use `GL_TEXTURE_LOD_BIAS` in `pgraph_bind_textures`?

```
GL_TEXTURE_LOD_BIAS
params specifies a fixed bias value that is to be added to the level-of-detail parameter for the texture before texture sampling. The specified value is added to the shader-supplied bias value (if any) and subsequently clamped into the implementation-defined range [−biasmax,biasmax], where biasmax is the value of the implementation defined constant GL_MAX_TEXTURE_LOD_BIAS. The initial value is 0.0.
```

### xemu Version

My near head development version (I'm confident that I have made no changes that would've removed handling of LOD bias)

Version: 0.6.2-109-ghttps://github.com/mborgerson/xemu/commit/a16eea7d86a1cbe5f6c9cfb6b076839abd64ea7dd86
Branch: work
Commit: a16eea7
Date: Sat Mar 12 06:38:59 AM UTC 2022

### System Information

"cpu": "Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz",
"gl_renderer": "NVIDIA GeForce GTX 1070/PCIe/SSE2",
"gl_shading_language_version": "4.00 NVIDIA via Cg compiler",
"gl_vendor": "NVIDIA Corporation",
"gl_version": "4.0.0 NVIDIA 470.103.01",
"os_platform": "Linux",
"os_version": "Ubuntu 21.10",

### Additional Context

_No response_

### LINKED ISSUE #973: Fatal Frame black lines next to the hair
### Title

https://xemu.app/titles/54430004/#Fatal-Frame-Zero-Special-Edition

### Bug Description

During the cutscenes, black lines are visible around the hair.

### Expected Behavior

xemu-2022-05-24-19-59-30
xemu-2022-05-24-15-07-11
xemu-2022-05-24-14-53-40
xemu-2022-05-24-14-48-12

### xemu Version

0.7.19

### System Information

Windows 11 Pro x64 21H2
AMD Ryzen 5 3600 4.2 Ghz
MSI Radeon VEGA 64 8 Gb HBM2 
22.5.1

### Additional Context

_No response_

### LINKED ISSUE #1110: Crash 'n' Burn Graphical issues
### Title

https://xemu.app/titles/45530014/#Crash-n-Burn

### Bug Description

Firstly, the outline around the trees is too strong, giving them an odd appearance. The Smoke effect has some artefacts lines thought them. Third, the road was rendered incorrect, where the pieces of the road which were rebuilt have a weird horizontal grid going through them, also seen on some side pieces of the pavement and are also black when at certain distances. Lastly, the bridge is rendered incorrectly.
Xemu (The tree):
xemu-2022-06-26-02-24-04
Xemu (The road)
xemu-2022-07-03-09-09-03

Xemu(The smoke) :
xemu-2022-06-26-02-22-26
Xemu(Top of the bridge is rendered incorrectly at both distances)
Far
xemu-2022-06-26-02-23-32
Close
xemu-2022-06-26-02-22-56

### Expected Behavior

[Trees should look like](https://youtu.be/Zg81Z-YqLkE?t=397)
[Road should look like](https://youtu.be/Zg81Z-YqLkE?t=247)
[What the smoke should look like](https://youtu.be/Zg81Z-YqLkE?t=353)
[What the Top of the bridge meant to look like](https://youtu.be/Zg81Z-YqLkE?t=275)

### xemu Version

Version: 0.7.49
Branch: master
Commit: https://github.com/mborgerson/xemu/commit/b3abb982e82edbbb142a2c275b893e7f62b10661
Date: Sat Jun 25 06:50:26 UTC 2022

### System Information

Field | Value
-- | --
OS | Windows 10
CPU | AMD Ryzen 5 2600 Six-Core Processo
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 512.95

### Additional Context

I know I shouldn't use the fusion emulator as a comparison as it has its own issues but that was all I could find on youtube on Xbox gameplay of the game with same map. Here renderdoc for debbuging 

Floor and tree renderdoc : https://drive.google.com/file/d/1QvyLOqc6w6f-NK4krNb4Rad67wFAy2H3/view?usp=sharing

Smoke Renderdoc  : https://drive.google.com/file/d/1BvaD8PdYsMT0M0KSPvvVdIbJj6h9PtGw/view?usp=sharing

### LINKED ISSUE #1204: Enter the matrix graphical issue
### Title

https://xemu.app/titles/49470022/#Enter-the-Matrix

### Bug Description

The character Ghost hair has a white line going through his hair not present on og xbox
xemu-2022-07-25-23-30-42
 

### Expected Behavior

https://youtu.be/3BtWBCfQ-Uw?t=851

### xemu Version

Version: 0.7.64
Branch: master
Commit: https://github.com/mborgerson/xemu/commit/248fc788c177e7b01ec1455b2005ee339332edbf
Date: Tue Jul 19 01:06:48 UTC 2022

### System Information

<html><body>

Field | Value
-- | --
OS | Windows 10
CPU | AMD Ryzen 5 2600 Six-Core Processor
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 512.95

</body>
</html>

### Additional Context

Here a renderdoc : https://drive.google.com/file/d/1k8FHTV-t8fubl68-yY_g9-0yx4FUw0_i/view?usp=sharing

### LINKED ISSUE #2377: TY the Tasmanian Tiger 2: Bush Rescue Text aliasing bug
### Title

https://xemu.app/titles/45410063/#TY-the-Tasmanian-Tiger-2-Bush-Rescue
https://xemu.app/titles/41560055/#TY-the-Tasmanian-Tiger-Night-of-the-Quinkan

### Bug Description

text look very grainy at 1x resolution scale compared to hardware. Look at copyright at bottom where most standouts 

1x
Image

Seem to look correct at 3x and higher

Image

### Expected Behavior

Should match hardware
Hardware
https://www.youtube.com/watch?v=zpMs4kIluXI

### xemu Version

V0.8.96

### System Information

OS | Windows 10
CPU | AMD Ryzen 5 5700x Eight-Core Processoer
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 570.133.07
Render | Opengl

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by abaire**
Fixes #767
Fixes #973
Fixes #1110
Fixes #1204
Fixes #2377

Tests: https://github.com/abaire/nxdk_pgraph_tests/blob/2aa0cb89543f3853a3830ba15a03c9f7dad58d69/src/tests/texture_lod_bias_tests.h#L1

HW results: https://abaire.github.io/nxdk_pgraph_tests_golden_results/results/Texture_LOD_Bias/index.html

PR results: https://github.com/abaire/xemu-dev_pgraph_test_results/blob/fix/implements_lod_bias/results/xemu-0.8.101-1-g3ece4e2a17-fix_implements_lod_bias-3ece4e2a170f38aef3f220ab007b090bbb29233b/Darwin_arm64/gl_Apple_Apple_M3_Max/gslv_4.10/Texture_LOD_Bias/LODBias.png

### CODE REVIEW

**Comment by Triticum0** [comment]
Seems to improve ground texture quality of Quantum Redshift. Though rather subtle
Masters
xemu-2025-09-18-20-46-58

PR
xemu-2025-09-18-20-59-19

**Comment by abaire** [comment]
@Triticum0 excellent, thanks for testing!

Could you also check Vulkan with the newest build? I don't have access to a VK capable machine at the moment and put in a prospective fix.

**Comment by Triticum0** [comment]
Seems to fix Burnout-3-Takedown ground texture quality too.
Masters
xemu-2025-09-18-21-30-56


PR
xemu-2025-09-18-21-31-36

Tested vulkan matches opengl didn't crash and looked identical to opengl.

**Comment by Triticum0** [comment]
Also tested crash and burn as well Wreckless The Yakuza Missions Both seem to be unrelated.

**Comment by abaire** [comment]
Thanks! I'll take a look at the traces you added to #2385, we might want to split them into a separate issue if they're due to a novel issue.

**Comment by Triticum0** [comment]
Opps actually fixes Crash 'N' Burn floor rendering and tree rendering. Look at outline around far floor textures and outline around 2d tree texture. #1110

Masters
xemu-2025-09-18-22-28-10

PR
xemu-2025-09-18-22-28-29

~~Doesn't fix railing above the track. only realise other issues where fixed when double checking to get a capture.~~

~~Hardware screenshot from loading screen~~

xemu-2025-09-18-22-32-27
Ingame
xemu-2025-09-18-22-32-31

~~See theirs 5 parts in-game rails but on screenshot there at least double. don't know if its related send capture soon.~~ Found a hardware capture actually occurs on hardware https://www.youtube.com/watch?v=KIHMt-TKgYk

**Comment by Triticum0** [comment]
Renderdoc are on this issue if your interested have add new one for the railing issue as I missed it before

**Comment by Triticum0** [comment]
Doesn't fix Racing Evoluzione/Apex ground texture issue.

**Comment by Triticum0** [comment]
Fixes #2377
Masters
xemu-2025-09-18-23-02-56


PR
xemu-2025-09-18-23-01-37

**Comment by Triticum0** [comment]
Fixed metal mesh overhead sign next to Xicat logo rendering incorrectly. on Motor Trend Presents Lotus Challenge.
Masters
xemu-2025-09-18-23-13-47

PR
xemu-2025-09-18-23-14-00

Hopefully why car blue or green could be looked at only happens with no shader cache.

Other Issues in #1228 are unaffected

**Comment by abaire** [comment]
@Triticum0 just to confirm, does this fully resolve #1110 or are there still remaining issues? I don't want to accidentally close out that issue if there is still work to be done.

**Comment by Triticum0** [comment]
Create new issue which supersede old issue with remaining issues so you can close it. other issue unrelated so I will move it

**Comment by Triticum0** [comment]
Improves the behavior of burnout 2 grass texture. #1161
Master
xemu-2025-09-19-00-14-19

PR
xemu-2025-09-19-00-13-46

No 100% sure if it matches hardware seem behavior present on hardware but not if it the same. need hardware capture to verify. here video where you can see line on hardware https://youtu.be/HGxRSVldAHk?t=333

@abaire Leave it to you judgment where you want to close the issue. the other issues on the pr either occur on hardware or are already fixed so can be closed if you thing the fix sufficient for bug above.

**Comment by Triticum0** [comment]
#2437 supersedes https://github.com/xemu-project/xemu/issues/1110 you can close it when it merged to masters.

**Comment by abaire** [comment]
> Improves the behavior of burnout 2 grass texture. #1161 
> @abaire Leave it to you judgment where you want to close the issue. the other issues on the pr either occur on hardware or are already fixed so can be closed if you thing the fix sufficient for bug above.

Does the Z-fighting mentioned not occur anymore? I assumed that bug would need coldhex's #2240 to fix some parts of it. We might need to break that bug up into separate issues, maybe we can just do that after this change is merged and leave off whatever is fixed by LOD biasing.


> #2437 supersedes #1110 you can close it when it merged to masters.
Perfect, marked #1110 as fixed by this; thanks!

**Comment by Triticum0** [comment]
It hard to see but It also occurs on hardware https://youtu.be/HGxRSVldAHk?t=502 so you can close that too. ask cold-hex about similar issue and he mention it occurred on hardware so in most of my old z-fighting I mentioned weren't valid.

**Comment by Triticum0** [comment]
Fixes rendering on distance building looking blurry on Driver: Parallel Lines. you can actually see windows on distance side buildings.
Master
xemu-2025-09-19-12-14-03


PR
xemu-2025-09-19-12-14-21

File: hw/xbox/nv2a/pgraph/vk/texture.c [hunk 1]
```diff
@@ -1356,7 +1365,8 @@ static void create_texture(PGRAPHState *pg, int texture_idx)
                                        VK_SAMPLER_MIPMAP_MODE_LINEAR,
         .minLod = mipmap_en ? MIN(state.min_mipmap_level, state.levels - 1) : 0.0,
         .maxLod = mipmap_en ? MIN(state.max_mipmap_level, state.levels - 1) : 0.0,
-        .mipLodBias = 0.0,
+        .mipLodBias = convert_lod_bias(
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/vk/texture.c]: Absolute value needs to be clamped to device limits (see `VkPhysicalDeviceLimits::maxSamplerLodBias`)

File: hw/xbox/nv2a/pgraph/gl/texture.c [hunk 2]
```diff
@@ -107,6 +107,15 @@ static bool check_texture_possibly_dirty(NV2AState *d,
     return possibly_dirty;
 }
 
+static inline float convert_lod_bias(uint32_t lod_bias)
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/gl/texture.c]: If implementation is identical between renderers, prefer to have this in common code

File: hw/xbox/nv2a/pgraph/gl/texture.c [hunk 3]
```diff
@@ -120,6 +129,8 @@ static void apply_texture_parameters(TextureBinding *binding,
     unsigned int addru = GET_MASK(address, NV_PGRAPH_TEXADDRESS0_ADDRU);
     unsigned int addrv = GET_MASK(address, NV_PGRAPH_TEXADDRESS0_ADDRV);
     unsigned int addrp = GET_MASK(address, NV_PGRAPH_TEXADDRESS0_ADDRP);
+    unsigned int lod_bias =
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/gl/texture.c]: nit: Prefer to group filter params

File: hw/xbox/nv2a/pgraph/gl/texture.c [hunk 4]
```diff
@@ -146,6 +157,10 @@ static void apply_texture_parameters(TextureBinding *binding,
                         pgraph_texture_mag_filter_gl_map[mag_filter]);
         binding->mag_filter = mag_filter;
     }
+    if (lod_bias != binding->lod_bias) {
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/gl/texture.c:151]: `binding->lod_bias` not initialized?

File: hw/xbox/nv2a/pgraph/gl/renderer.h [hunk 5]
```diff
@@ -80,6 +80,7 @@ typedef struct TextureBinding {
     bool border_color_set;
     GLenum gl_target;
     GLuint gl_texture;
+    uint32_t lod_bias;
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/gl/renderer.h]: nit: Prefer to group filter params

Comment (abaire) [reply hw/xbox/nv2a/pgraph/gl/renderer.h]: Done

File: hw/xbox/nv2a/pgraph/gl/texture.c (hunk 2 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/gl/texture.c]: Done.

File: hw/xbox/nv2a/pgraph/gl/texture.c (hunk 3 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/gl/texture.c]: Done.

File: hw/xbox/nv2a/pgraph/gl/texture.c (hunk 4 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/gl/texture.c:151]: Good catch, done.

File: hw/xbox/nv2a/pgraph/vk/texture.c (hunk 1 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/vk/texture.c]: Done, I think; will need to see if my change builds on CI since I can't build VK locally right now.

File: hw/xbox/nv2a/pgraph/vk/texture.c [hunk 6]
```diff
@@ -1336,6 +1336,12 @@ static void create_texture(PGRAPHState *pg, int texture_idx)
         min_filter == NV_PGRAPH_TEXFILTER0_MIN_BOX_NEARESTLOD ||
         min_filter == NV_PGRAPH_TEXFILTER0_MIN_TENT_NEARESTLOD;
 
+    float lod_bias = pgraph_convert_lod_bias_to_float(
+        GET_MASK(filter, NV_PGRAPH_TEXFILTER0_MIPMAP_LOD_BIAS));
+    if (lod_bias > r->device_props.limits.maxSamplerLodBias) {
+        lod_bias = r->device_props.limits.maxSamplerLodBias;
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/vk/texture.c:1342]: Need to also handle negative bias clamp (absolute value must not exceed maxSamplerLodBias)

Comment (abaire) [reply hw/xbox/nv2a/pgraph/vk/texture.c:1342]: Oops, misread your comment, sorry!

That said, is it actually necessary to manually clamp these at the application level?

The docs lead me to believe that the driver would handle the clamping, since it ends up being a summation of the bias and the sampling so simply clamping the bias may be insufficient to remain in bounds anyway:
```
maxSamplerLodBias is the maximum absolute sampler LOD bias. The sum of the mipLodBias member of the [VkSamplerCreateInfo](https://registry.khronos.org/vulkan/specs/latest/man/html/VkSamplerCreateInfo.html) structure and the Bias operand of image sampling operations in shader modules (or 0 if no Bias operand is provided to an image sampling operation) are clamped to the range [-maxSamplerLodBias,+maxSamplerLodBias]. See https://registry.khronos.org/vulkan/specs/latest/html/vkspec.html#samplers-mipLodBias.
```

Comment (mborgerson) [reply hw/xbox/nv2a/pgraph/vk/texture.c:1342]: > is it actually necessary

Maybe, maybe not. According to [spec](https://docs.vulkan.org/spec/latest/chapters/samplers.html#VUID-VkSamplerCreateInfo-mipLodBias-01069): The absolute value of mipLodBias must be less than or equal to VkPhysicalDeviceLimits::maxSamplerLodBias

> the driver would handle the clamping

In general, Vulkan drivers are a lot less forgiving. Even when operating fully within spec, they can be problematic. If we are lucky, a case like this would trigger a validation warning and have no other impact, if we are unlucky it results in some random overflow and a crash, so it's best to follow spec guidance when populating struct params.

File: hw/xbox/nv2a/pgraph/texture.h [hunk 7]
```diff
@@ -64,4 +64,13 @@ hwaddr pgraph_get_texture_palette_phys_addr_length(PGRAPHState *pg, int texture_
 TextureShape pgraph_get_texture_shape(PGRAPHState *pg, int texture_idx);
 size_t pgraph_get_texture_length(PGRAPHState *pg, TextureShape *shape);
 
+static inline float pgraph_convert_lod_bias_to_float(uint32_t lod_bias)
+{
+    int sign_extended_bias = lod_bias;
+    if (lod_bias & (1 << 12)) {
```
Comment (PatrickvL) [inline hw/xbox/nv2a/pgraph/texture.h:70]: Does this 12th bit have any significant name or is it merely tested to "or in" the subsequent 0x00001FFF const? And whats the significance of that? Fixed point ceiling, because of the final division by 256.0f ? Xemu is not strong in code comments but this looks like a hard to maintain bit of logic of anyone ever needs to revisit this again.

Comment (PatrickvL) [reply hw/xbox/nv2a/pgraph/texture.h:70]: Never mind, it is actually doing sign extension on the 12th bit onwards, assuming the trust contains a 12 bit signed fixed point number (4 integer + 8 fractional bits, in twos complement, a.k.a. Q3.8). Apparently there's no helper function for that yet.

Just 1 thought: the output range is now -8.0 to +7.99609375 which is not exactly 8.0
Would that be any problem?

**Comment by Triticum0** [comment]
Fixes #973
Before
170250344-168577d3-2c75-4dcd-9572-f190646678eb

After
xemu-2025-09-20-21-47-49

**Comment by Triticum0** [comment]
Fixes #1204
Before
xemu-2022-07-25-23-30-42
After
xemu-2025-09-20-23-49-05

File: hw/xbox/nv2a/pgraph/texture.h (hunk 7 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/texture.h:70]: I don't think there are many places where 5.8 fixed point numbers are used and it doesn't seem clearly useful to bother with a more complicated generic sign extended fixed point -> float conversion function.

I also doubt it'd 7.99609375 versus 8 would result in noticeable differences if it actually ends up being materially different from how the nv2a HW handles the 5.8 value. I'd guess there's likely more variance across HW/drivers than that fractional delta in any case.

**Comment by Triticum0** [comment]
Should Fix #1930 but haven't tested it

**Comment by mborgerson** [comment]
Thanks!

**Comment by Triticum0** [comment]
Did fix #1930

**Comment by Triticum0** [comment]
Fixed ground texture on Motogp 3
Before
xemu-2026-02-04-00-22-01

After
xemu-2026-02-04-00-22-39
