### PR TITLE
nv2a: Handle texture dimensions not divisible by 4 in S3TC decoder

### LINKED ISSUE #1830: Vulkan: Midtown Madness 3 - Graphic corruption on part of the Profile menu
### Title

https://xemu.app/titles/4d53002a/#Midtown-Madness-3 MS-042 [4d53002a]

### Bug Description

Parts profile menu have some corruption that is only present in the Vulkan backend, the OpenGL displays the menu properly.

Steps to produce:
1.) Make sure that the backend is set to Vulkan
2.) To ensure that you can follow along with the steps, make sure no other Midtown Madness 3 save is on the Xbox HDD image. The steps assume you haven't made a profile yet.
3.) Load the game up.
4.) Press Start button to skip the opening FMVs and get to a loading screen.
5.) When you get to the title screen, press the Start button. The Profile menu should appear that will ask if you want to rename the profile for Player1.

Screenshot:
Red arrows added by me to point out the issue.
image

### Expected Behavior

The profile menu is expected to have no black stripes or bars and should look a lot more solid, like in the OpenGL backend.

Screenshot:
image

### xemu Version

Version:      0.8.1
Branch:       master
Commit:       8f478e017a0f7bac7d72d4abe23e77233f221bce
Date:         Tue Dec 31 10:20:49 UTC 2024

### System Information

CPU:          AMD Ryzen 7 5800X 8-Core Processor             
OS Platform:  Windows
OS Version:    22H2
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce RTX 3080/PCIe/SSE2
Driver:       4.0.0 NVIDIA 566.36
Shader:       4.00 NVIDIA via Cg compiler

### Additional Context

A profile is immediately made even if you don't name it. So to repeat the steps to reproduce above, you need to delete the saved game every time. However, you can access the menu again by going to "PROFILES" from the main menu, select DELETE, and the menu that appears to confirm deletion will have the issue as well.

image

### PR DESCRIPTION
**Pull request by wilkovatch**
Fixes #1830 by keeping the actual texture size when decompressing 2D textures (e.g. 1x32 instead of 4x32), thus eliminating the need for the call to glPixelStorei (which has no equivalent on Vulkan, hence the bug)

Thanks @coldhex for the heads up

Before (on Vulkan):
xemu-2025-03-11-20-14-58

After:
xemu-2025-03-11-20-15-52

### CODE REVIEW

File: hw/xbox/nv2a/pgraph/s3tc.c [hunk 1]
```diff
@@ -209,22 +210,24 @@ uint8_t *s3tc_decompress_2d(enum S3TC_DECOMPRESS_FORMAT color_format,
                             const uint8_t *data, unsigned int width,
                             unsigned int height)
 {
-    assert((width > 0) && (width % 4 == 0));
-    assert((height > 0) && (height % 4 == 0));
-    int num_blocks_x = width / 4, num_blocks_y = height / 4;
+    assert(width > 0);
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/s3tc.c:215]: We should also apply this change to `s3tc_decompress_3d`

**Comment by mborgerson** [comment]
A minor nit about the commit title: It's unclear what "actual texture size" means. I'll propose an alternative title that's a bit more clear: `nv2a: Handle texture dimensions not divisible by 4 in S3TC decoder` or `nv2a: Handle virtual texture dimensions in S3TC decoder`

**Comment by mborgerson** [comment]
Awesome, thanks!
