### PR TITLE
nv2a: Handle anisotropic filter setting

### LINKED ISSUE #2385: Mipmapping Issues (missing emulation of LOD bias and anisotropic filtering)
### Title

https://xemu.app/titles/4d530015/#Quantum-Redshift
https://xemu.app/titles/4156000a/#Wreckless-The-Yakuza-Missions
https://xemu.app/titles/4541005b/#Burnout-3-Takedown

### Bug Description

Racing games such as Quantum Redshift and Wreckless Yakuza Missions have an issue where the road ahead is blurry by what it looks like mipmapping. I remember a while ago testing Burnout 3 and it also showed similar issues so I don't know to what extend other racing games are affected.

Image
Image

### Expected Behavior

It should not have any blurring. The roads and other nearby textures.

Image
Image

### xemu Version

0.8.96

### System Information

Windows 11 24H2

### Additional Context

Using a Ryzen 9 7940HS and its iGPU.

### LINKED ISSUE #2444: Wreckless: The Yakuza Missions Mipmap Issues
### Title

https://xemu.app/titles/4156000a/#Wreckless-The-Yakuza-Missions
https://xemu.app/titles/42550004/#Double-S-T-E-A-L-The-Second-Clash

### Bug Description

This game and it sequel seem to have very poor mipmap quality as you get further that worse than what you get on hardware. First game much worse than the second even object close to the player are burry

Wreckless: The Yakuza Missions

Image

Double S.T.E.A.L. The Second Clash

Image

### Expected Behavior

Wreckless: The Yakuza Missions

https://youtu.be/z8PjB0AH32k?t=91

Double S.T.E.A.L. The Second Clash

https://youtu.be/V2A6tVnHPuA?list=PLOU4Sp0k5y_dueUMNPGz5euU2OSrWkol_&t=67

### xemu Version

v0.8.101

### System Information

Field | Value
-- | --
OS | Windows 10
CPU | AMD Ryzen 5 5700x Eight-Core Processoe
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 581.29
Render | Opengl

### Additional Context

Renderdocs

### PR DESCRIPTION
**Pull request by abaire**
Implements handling of anisotropic filter level from SET_TEXTURE_CONTROL0.

Fixes #2444 (in conjunction with PR #2435 for `STEAL`)
Fixes #2385 (for whatever isn't already fixed by PR #2435)

Tests: https://github.com/abaire/nxdk_pgraph_tests/blob/4dc2b8f16749d0d9b9bd9e8c90b649944f96a662/src/tests/texture_anisotropy_tests.h#L10

HW results: https://abaire.github.io/nxdk_pgraph_tests_golden_results/results/Texture_anisotropy/index.html

PR results: https://abaire.github.io/xemu-dev_pgraph_test_results/fix_2444_respect_anisotropic_filter_level/index.html - Please note that there was a bleedover error in the test suite when I first ran the suite that tainted the diff for the `Texture_perspective_enable` result. If you manually compare the `Source` and `xemu Golden` images they are now identical.

### CODE REVIEW

File: hw/xbox/nv2a/pgraph/vk/texture.c [hunk 1]
```diff
@@ -1346,9 +1353,8 @@ static void create_texture(PGRAPHState *pg, int texture_idx)
             GET_MASK(address, NV_PGRAPH_TEXADDRESS0_ADDRV)),
         .addressModeW = (state.dimensionality > 2) ? lookup_texture_address_mode(
             GET_MASK(address, NV_PGRAPH_TEXADDRESS0_ADDRP)) : 0,
-        .anisotropyEnable = VK_FALSE,
-        // .anisotropyEnable = VK_TRUE,
-        // .maxAnisotropy = properties.limits.maxSamplerAnisotropy,
+        .anisotropyEnable = max_anisotropy > 1,
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/vk/texture.c]: Before this can be `VK_TRUE`, the `samplerAnisotropy` device feature will need to be enabled. Then check that it is actually enabled via `r->enabled_physical_device_features.samplerAnisotropy`.

See here: https://github.com/xemu-project/xemu/blob/59626b1f5dc038c69e0044d87d7bd1cd6a1dce05/hw/xbox/nv2a/pgraph/vk/instance.c#L549

File: hw/xbox/nv2a/pgraph/vk/texture.c [hunk 2]
```diff
@@ -1101,6 +1101,13 @@ static void create_texture(PGRAPHState *pg, int texture_idx)
         pgraph_reg_r(pg, NV_PGRAPH_BORDERCOLOR0 + texture_idx * 4);
     bool is_indexed = (state.color_format ==
             NV097_SET_TEXTURE_FORMAT_COLOR_SZ_I8_A8R8G8B8);
+    uint32_t xbox_max_anisotropy =
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/vk/texture.c]: * `xbox_` prefix is inconsistent with other fields
* Will need to be added to texture key for caching. See below at line 1127

File: hw/xbox/nv2a/pgraph/vk/texture.c [hunk 3]
```diff
@@ -1101,6 +1101,13 @@ static void create_texture(PGRAPHState *pg, int texture_idx)
...
+        1 << (GET_MASK(pgraph_reg_r(pg, NV_PGRAPH_TEXCTL0_0 + texture_idx*4),
+                       NV_PGRAPH_TEXCTL0_0_MAX_ANISOTROPY));
+    uint32_t max_anisotropy =
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/vk/texture.c]: Simplify with `MIN`

File: hw/xbox/nv2a/pgraph/vk/texture.c (hunk 2 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/vk/texture.c]: Done.

Is the plan for the nearby FIXME to pull the sampler out of the texture binding?

File: hw/xbox/nv2a/pgraph/vk/texture.c (hunk 3 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/vk/texture.c]: Done, also moved closer to where it's actually used.

File: hw/xbox/nv2a/pgraph/vk/texture.c (hunk 1 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/vk/texture.c]: Done? I don't have a way to actually test.

Should we sort those desired features alphabetically? I can imagine it'll become hard to tell what has been requested at a glance as the list gets longer.

Comment (mborgerson) [reply hw/xbox/nv2a/pgraph/vk/texture.c]: >  sort those desired features alphabetically?

Probably yes

File: hw/xbox/nv2a/pgraph/vk/texture.c (hunk 2 above)
Comment (mborgerson) [reply hw/xbox/nv2a/pgraph/vk/texture.c]: > Is the plan for the nearby FIXME to pull the sampler out of the texture binding?

They need not be coupled, but it's also not a high priority. Keeping them together simplifies lookup/expiration at the cost of inflated sampler counts.

File: hw/xbox/nv2a/pgraph/gl/texture.c [hunk 4]
```diff
@@ -181,6 +182,8 @@ static void apply_texture_parameters(TextureBinding *binding,
         needs_border_color = needs_border_color || binding->addrp == NV_PGRAPH_TEXADDRESS0_ADDRU_BORDER;
     }
 
+    glTexParameterf(binding->gl_target, GL_TEXTURE_MAX_ANISOTROPY, max_anisotropy);
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/gl/texture.c]: Technically `GL_TEXTURE_MAX_ANISOTROPY` is not GL 4.0 core--it comes from the `ARB_texture_filter_anisotropic` extension.

The original extension was `EXT_texture_filter_anisotropic` and used the `GL_TEXTURE_MAX_ANISOTROY_EXT` token, which have identical numeric values.

Though it is ubiquitous, it would be good practice to confirm `GL_EXT_texture_filter_anisotropic` extension is present (See `pgraph_gl_init`) before using it.

File: hw/xbox/nv2a/pgraph/vk/texture.c [hunk 5]
```diff
@@ -1354,9 +1360,9 @@ static void create_texture(PGRAPHState *pg, int texture_idx)
             GET_MASK(address, NV_PGRAPH_TEXADDRESS0_ADDRV)),
         .addressModeW = (state.dimensionality > 2) ? lookup_texture_address_mode(
             GET_MASK(address, NV_PGRAPH_TEXADDRESS0_ADDRP)) : 0,
-        .anisotropyEnable = VK_FALSE,
-        // .anisotropyEnable = VK_TRUE,
-        // .maxAnisotropy = properties.limits.maxSamplerAnisotropy,
+        .anisotropyEnable = r->enabled_physical_device_features.wideLines &&
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/vk/texture.c]: Looks like a copy paste error. We need to check for `samplerAnisotropy` feature, not `wideLines` here.

File: hw/xbox/nv2a/pgraph/gl/texture.c (hunk 4 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/gl/texture.c]: Done; added a struct to track extension use similar to VK enabled features.

File: hw/xbox/nv2a/pgraph/vk/texture.c (hunk 5 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/vk/texture.c]: Stupid mistake/autosuggest fail, done.

File: hw/xbox/nv2a/pgraph/vk/texture.c (hunk 1 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/vk/texture.c]: Done.

File: hw/xbox/nv2a/pgraph/vk/instance.c [hunk 6]
```diff
@@ -540,12 +540,13 @@ static bool create_logical_device(PGRAPHState *pg, Error **errp)
...
-        F(geometryShader, true),
-        F(shaderTessellationAndGeometryPointSize, true),
         F(depthClamp, true),
-        F(occlusionQueryPrecise, true),
         F(fillModeNonSolid, true),
+        F(geometryShader, true),
+        F(occlusionQueryPrecise, true),
+        F(samplerAnisotropy, false),
+        F(shaderClipDistance, true),
+        F(shaderTessellationAndGeometryPointSize, true),
```
Comment (PatrickvL) [inline hw/xbox/nv2a/pgraph/vk/instance.c:549]: These changes seem unrelated to the actual work. Consider moving this to a separate pull request, or elaborate why it should be in here

Comment (abaire) [reply hw/xbox/nv2a/pgraph/vk/instance.c:549]: These changes are related to the PR; `samplerAnisotropy` was added as part of emulating the max anisotropy field. 

As confirmed previously in this code review, these are intended to be kept alphabetized to make it easier to determine what features are and are not being requested. In my opinion the overhead of yet another PR for a tiny additional cleanup is not justified.

**Comment by mborgerson** [comment]
Thanks!
