### PR TITLE
pgraph: Enables 16-bit floating point z-buffer mode.

### LINKED ISSUE #60: NV097_SET_SURFACE_FORMAT_ZETA_Z16 needs verification
The Voodoo Vince demo on the Crimson Skies disc crashes upon trying to go in-game after selecting play on the main menu. This is the resulting error:

ERROR:D:/a/xemu/xemu/hw/xbox/nv2a/pgraph.c:2482:pgraph_method: assertion failed: (0)
Bail out! ERROR:D:/a/xemu/xemu/hw/xbox/nv2a/pgraph.c:2482:pgraph_method: assertion failed: (0)

Titles: 4d53005f, 4d530021, 43430002, 43430009

https://xemu.app/titles/4156000f/#Star-Wars-Obi-Wan
https://xemu.app/titles/494c0002/#Braveknight-Leverant-Eiyuuden
https://xemu.app/titles/4b4e0003/#ESPN-NFL-PrimeTime-2002
https://xemu.app/titles/43430005/#Group-S-Challenge
https://xemu.app/titles/4b4e0019/#Dance-Dance-Revolution-Ultramix
https://xemu.app/titles/41430003/#Legends-of-Wrestling
https://xemu.app/titles/4143000f/#Legends-of-Wrestling-II
https://xemu.app/titles/4143001d/#Showdown-Legends-of-Wrestling
https://xemu.app/titles/4d570029/#Mortal-Kombat-Shaolin-Monks
https://xemu.app/titles/45530016/#Backyard-Wrestling-2-There-Goes-the-Neighborhood
https://xemu.app/titles/4d530034/#Inside-Pitch-2003
https://xemu.app/titles/424d0002/#Reign-of-Fire
https://xemu.app/titles/53450029/#Spikeout-Battle-Street
https://xemu.app/titles/41540001/#Touge-R

### PR DESCRIPTION
**Pull request by abaire**
Removes the verification assert when clearing 16-bit floating point z-buffer.

Tested via https://github.com/abaire/nxdk_pgraph_tests and for the most part the output produced by xemu very closely matches the output from a 1.0 XBOX (there are very minor differences in color blending that are also observable in normal texturing and do not appear to be related to z-buffering). Output of running the test against hardware can be found here: https://github.com/abaire/nxdk_pgraph_tests_golden_results

The main difference I observed is that on the XBOX, z values < `convert_f16_to_float(0x1000) == 0.0156250f` will all result in 0 being written to the depth buffer, whereas xemu seems to support all mappable values down to zero. This results in clear values < 0x1000 still rendering anything < `0.0156250f` on hardware but content being properly cleared on xemu. I'm not sure if this matters in practice as it only affects a small range of z-values with clipping disabled or with a 0 near-plane.

Fixes #60

### CODE REVIEW

File: hw/xbox/nv2a/vsh.c [hunk 1]
```diff
@@ -776,9 +776,15 @@ void vsh_translate(uint16_t version,
          * Note this makes the values in the depth buffer wrong. This should be
          * handled with gl_ClipDistance instead, but that has performance issues
          * on OS X.
+         *
+         * This conversion is performed at double precision to handle max depth
```
Comment (abaire) [inline hw/xbox/nv2a/vsh.c]: I think this is technically not necessary for the 16-bit buffer, but the z24 will fail with the clip range at maximum precision. I can throw this into a future PR to address #322 if you'd prefer (it is necessary for anybody who wants to compare the full set of results against the hardware).

Comment (mborgerson) [reply hw/xbox/nv2a/vsh.c]: I thought I had resolved this precision issue already, but apparently not everywhere. I know it's still an issue on M1 at least. I'm okay to switch up to DP. Let's make this a separate commit and correct typo (z25->z24)

**Comment by mborgerson** [comment]
Thanks for the unit tests! Minor fixup and I'll merge

**Comment by mborgerson** [comment]
> The main difference I observed is that on the XBOX, z values < convert_f16_to_float(0x1000) == 0.0156250f will all result in 0 being written to the depth buffer, whereas xemu seems to support all mappable values down to zero. This results in clear values < 0x1000 still rendering anything < 0.0156250f on hardware but content being properly cleared on xemu. I'm not sure if this matters in practice as it only affects a small range of z-values with clipping disabled or with a 0 near-plane.

We should clamp the values if necessary to replicate HW behavior. We can do this in a follow up

File: hw/xbox/nv2a/vsh.c (hunk 1 above)
Comment (abaire) [reply hw/xbox/nv2a/vsh.c]: sg, will split it out.

**Comment by abaire** [comment]
> > The main difference I observed is that on the XBOX, z values < convert_f16_to_float(0x1000) == 0.0156250f will all result in 0 being written to the depth buffer, whereas xemu seems to support all mappable values down to zero. This results in clear values < 0x1000 still rendering anything < 0.0156250f on hardware but content being properly cleared on xemu. I'm not sure if this matters in practice as it only affects a small range of z-values with clipping disabled or with a 0 near-plane.
> 
> We should clamp the values if necessary to replicate HW behavior. We can do this in a follow up

Sounds good. I'm somewhat wary that there may be some dumb mistake with my pgraph config that is causing the xbox to clamp the exponent-less values, but I guess it makes sense that if my test is doing something wrong in setting up the hardware it's doing the same wrong thing setting up xemu so the behavior should probably match. If there's anybody out there with more knowledge of nv2a configuration that would like to take a look, it'd be very much appreciated :)

**Comment by mborgerson** [comment]
FYI I've edited commit message.

Thanks for the contribution!
