### PR TITLE
nv2a: Apply texture parameters when reusing textures

### LINKED ISSUE #1034: Meta : Game with Texture Stretching
### Bug Description

Some games have Texture stretching on some objects
### Games Affected
[Rugby 2006](https://xemu.app/titles/45410087/#Rugby-06)
xemu-2022-06-24-22-16-07
[Charlie and the chocolate factory ](https://xemu.app/titles/54540081/#Charlie-and-the-Chocolate-Factory)
image
[Shenmue II](https://xemu.app/titles/4d530032/#Shenmue-II) #988
[~~F1 Career Challenge~~ Unrelated](https://xemu.app/titles/45410032/#F1-Career-Challenge)
[Men of Valor](https://xemu.app/titles/56550019/#Men-of-Valor)
### Expected Behavior

Should not stretch

### xemu Version

Version: 0.7.28
Branch: master
Commit:https://github.com/mborgerson/xemu/commit/176b574403e0f4a08bfb1f8ab58e0f819a45cf81
Date: Fri Jun 3 21:40:57 UTC 2022

### System Information

Field | Value
-- | --
OS | Windows 10
CPU | AMD Ryzen 5 2600 Six-Core Processo
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 512.95

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by abaire**
Fixes the edge case where a texture is reusable but has modified usage
parameters (e.g., `GL_TEXTURE_WRAP_S`). Prior to this change, texture
parameters would be cached permanently until the texture was recreated.

Fixes #1034

[Test](https://github.com/abaire/nxdk_pgraph_tests/blob/30c84f739b5a4d628778b23aec2be70162875d5d/src/tests/texture_border_tests.cpp#L323)
[HW results](https://github.com/abaire/nxdk_pgraph_tests_golden_results/wiki/Results-Texture_border)

### CODE REVIEW

File: hw/xbox/nv2a/pgraph.c [hunk 1]
```diff
@@ -6587,6 +6649,16 @@ static void pgraph_bind_textures(NV2AState *d)
             if (reusable) {
                 glBindTexture(pg->texture_binding[i]->gl_target,
                               pg->texture_binding[i]->gl_texture);
+                apply_texture_parameters(pg->texture_binding[i]->gl_target,
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph.c]: Let's cache the addressing, filtering, etc options in the texture binding to avoid resetting these parameters when they are unchanged

Comment (abaire) [reply hw/xbox/nv2a/pgraph.c]: Done.

**Comment by abaire** [comment]
CI failure doesn't seem to be related to this PR:
```
In file included from ../ui/xemu-settings.cc:29:
../genconfig/cnode.h:36:10: fatal error: toml.hpp: No such file or directory
   36 | #include <toml.hpp>
      |          ^~~~~~~~~~
```

Scratch that, PR accidentally reverted a submodule.

File: hw/xbox/nv2a/nv2a_int.h [hunk 2]
```diff
@@ -177,6 +177,14 @@ typedef struct TextureBinding {
     int draw_time;
     uint64_t data_hash;
     unsigned int scale;
+    unsigned int dimensionality;
```
Comment (mborgerson) [inline hw/xbox/nv2a/nv2a_int.h]: Not needed (never read)

File: hw/xbox/nv2a/nv2a_int.h [hunk 3]
```diff
@@ -177,6 +177,14 @@ typedef struct TextureBinding {
...
+    unsigned int min_filter;
```
Comment (mborgerson) [inline hw/xbox/nv2a/nv2a_int.h:180]: Let's do {min,mag}_filter and addr{u,v,p} decode in the apply_texture_parameters function and reduce binding struct inflation from 5 ints to 2

File: hw/xbox/nv2a/nv2a_int.h (hunk 2 above)
Comment (abaire) [reply hw/xbox/nv2a/nv2a_int.h]: Removed.

File: hw/xbox/nv2a/nv2a_int.h (hunk 3 above)
Comment (abaire) [reply hw/xbox/nv2a/nv2a_int.h:180]: Done.
