### PR TITLE
nv2a: Prevent depth surface from being used as render buf

### LINKED ISSUE #1227: Dino Crisis 3 - Assertion Failed Error - failed `GL_FRAMEBUFFER_COMPLETE` check
### Title

https://xemu.app/titles/43430003/#Dino-Crisis-3

### Bug Description

As soon as the main menu loads, the emulator pauses and the error appears:

clicking on ignore you can keep playing, but even so, the error randomly appears when trying to access inventory. The problem is, if you're playing at fullscreen, the emulator crashes, you don't have the option to ignore it and continue playing

### Expected Behavior

Not show any error screens I believe

### xemu Version

Latest version

### System Information

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by abaire**
Fixes #1227

### CODE REVIEW

**Comment by abaire** [comment]
Looks like this was already fixed in the initial commit of the Vulkan renderer.

File: hw/xbox/nv2a/pgraph/gl/display.c [hunk 1]
```diff
@@ -385,6 +385,16 @@ void pgraph_gl_sync(NV2AState *d)
 
     /* FIXME: Sanity check surface dimensions */
 
+    /* Dino Crisis 3 appears to have a race condition where surface addresses
+     * are swapped between color and zeta use, leading to an occasional state
+     * where the surface in the VGA region is a depth format and unsuitable for
+     * display.
+     */
+    if (!surface->color) {
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/gl/display.c]: Let's simplify via merge with above line 381. Let's also drop the comment and track on the GitHub issue #1227

Comment (abaire) [reply hw/xbox/nv2a/pgraph/gl/display.c]: Done

**Comment by Triticum0** [comment]
#2161

**Comment by abaire** [comment]
> #2161

Does this fix it? 

If not I added some more debug logging to my work branch as part of tracking this one down that should give more insight into the failure.

**Comment by Triticum0** [comment]
Don't know just added it because I saw it when going though Graphics issues. I will test itwhen I get time.

**Comment by Triticum0** [comment]
I tested it and it still seem to crash using this build

**Comment by mborgerson** [comment]
Thanks!

**Comment by Triticum0** [comment]
oops #1597

**Comment by abaire** [comment]
> oops #1597

Can you expand on what "oops" means in this case? 

I gather from clicking through and reading the comment that this PR fixed #1597? Ideally when cross-linking PRs/issues the reason they're linked should be made obvious in the comment linking them.

**Comment by Triticum0** [comment]
>xemu-v0.7.115-x86_64.AppImage:` ../hw/xbox/nv2a/pgraph.c:5291: pgraph_render_display: Assertion `glCheckFramebufferStatus(GL_FRAMEBUFFER) == GL_FRAMEBUFFER_COMPLETE' failed.
Aborted (core dumped)

The assertion, i missed the game by mistake. and is working with Vulkan
 Same issue
