### PR TITLE
nv2a: Treat 0 SET_FRONT_FACE as CCW to match hw.

### LINKED ISSUE #321: Unknown front face
### Title Information
Titles: 
Whiplash (45530011)
Project: Snowblind (45530019)
https://xemu.app/titles/45530011/#Whiplash
https://xemu.app/titles/45530019/#Project-Snowblind

### Bug Description
Game crashes with this assertion before the intro
https://github.com/mborgerson/xemu/blob/bbcd5763e6204d6d1e109c2d19cfd794e3abf8e2/hw/xbox/nv2a/pgraph.c#L1707-L1708

Steps to reproduce this issue:
1. Insert disk
2. Game crashes

### Expected Behavior

It should make it into the intro

### Version
<ul>
<li>Version: build-202106020756( <a href="https://github.com/mborgerson/xemu/commit/3884b8d44b4bfaed73f26227cd88d7946e2dfaa5"><tt>3884b8d</tt></a>)</li>
<li>Last-known Working: Unknown</li>
</ul>
<h3>System Information</h3>

Field | Value
-- | --
OS | Windows 10 64-bit (21H1)
CPU | AMD Ryzen 5 2600 Six-Core Processor @ 3.40GHz
Graphics Device | AMD Radeon RX 5700 XT
Graphics Driver | 4.0.148202 Core Profile Context 21.3.2 27.20.15003.5017

### PR DESCRIPTION
**Pull request by abaire**
Treats a `SET_FRONT_FACE` of `0` as `CCW` to match observed behavior on HW (Xbox 1.0).

Test case: https://github.com/abaire/nxdk_pgraph_tests/blob/main/tests/front_face_tests.cpp

Fixes #321

### CODE REVIEW

File: hw/xbox/nv2a/pgraph.c [hunk 1]
```diff
@@ -1701,6 +1701,12 @@ DEF_METHOD(NV097, SET_FRONT_FACE)
...
         ccw = false; break;
+
+    case 0:
+        // Treat 0 as CCW to match Xbox behavior.
+        // This is known to be set by the following titles:
+        //   Whiplash (45530011)
+        //   Project Snowblind (45530019)
     case NV097_SET_FRONT_FACE_V_CCW:
         ccw = true; break;
     default:
```
Comment (abaire) [inline hw/xbox/nv2a/pgraph.c:1706]: From playing with a few random values, I suspect all invalid params are treated as CCW on hardware. Does it make sense to have the default warn and return CCW rather than assert? 

It seems like you'd probably have to jump through some hoops to get DirectX to send an invalid winding, so maybe these `0` sending titles are the only ones to worry about?

Comment (mborgerson) [reply hw/xbox/nv2a/pgraph.c:1706]: Can you confirm hardware actually does this? Set the value and read it back and see what you get. For other methods I've seen hardware drop the invalid value and retain whatever was programmed previously.

e.g. Set CW, then set some invalid value. Then check that it was set to CCW as you suggested, or whether it remains CW.

Comment (abaire) [reply hw/xbox/nv2a/pgraph.c:1706]: Yeah, I had the same thought and (manually) ran the tests out of order to verify that it seems to always force CCW.

I haven't dug into pbkit enough to know how to read the value back, do you happen to know off the top of your head? Otherwise I can modify the test to explicitly set CW and flush before setting the random value so what I did manually is automated.

Comment (abaire) [reply hw/xbox/nv2a/pgraph.c:1706]: And I take it back. I forgot that pbkit is reinitializing things under the hood between tests so my validation was invalid. I'm now forcibly setting CW prior to the value under test and you're correct, it just preserves the previously set value.

In light of this, maybe we should just remove the assert and have the default be a no-op?

Comment (mborgerson) [reply hw/xbox/nv2a/pgraph.c:1706]: Yes, here's an example of how this is handled elsewhere: https://github.com/mborgerson/xemu/blob/50a5368f473ea95482f94fd4c7edd1b2b9709179/hw/xbox/nv2a/pgraph.c#L1491

Let's follow the model here too

Comment (abaire) [reply hw/xbox/nv2a/pgraph.c:1706]: Cool, changed

**Comment by mborgerson** [comment]
Thanks
