### PR TITLE
nv2a: Fix CPU surface access callback race and use-after-free

### LINKED ISSUE #1881: Segfault in physmem.c::access_callback_address_matches
### Bug Description

When running the nxdk_pgraph_tests iso (`-s -dvd_path <iso_path>`), I often hit a segfault in `access_callback_address_matches`, with an invalid MemAccessCallback (`0x10000000000`) looking for 4 bytes at hwaddr `0xB01C000`. This doesn't happen everytime, but is ~80% reproducible.

I've tested both with the latest release of the pgraph tests (https://github.com/abaire/nxdk_pgraph_tests/releases/tag/v2025-01-23_16-45-41-546148502) and with a version from before the config file format changes (artifact https://github.com/abaire/nxdk_pgraph_tests/actions/runs/12934415733 can be regenerated from the "before_json_config" branch if needed)

I am able to reproduce this crash with older official AppImage releases as well; I tried a handful back through `xemu-v0.7.101-x86_64.AppImage` as well as `xemu-v0.8.10-x86_64.AppImage`

Stack trace:
```
access_callback_address_matches physmem.c:819
mem_check_access_callback_ramaddr physmem.c:885
mem_check_access_callback_vaddr physmem.c:877
mmu_watch_or_dirty cputlb.c:1719
mmu_lookup cputlb.c:1767
do_st4_mmu cputlb.c:2783
helper_stl_mmu ldst_common.c.inc:100
cpu_tb_exec cpu-exec.c:484
cpu_loop_exec_tb cpu-exec.c:934
cpu_exec_loop cpu-exec.c:1048
cpu_exec_setjmp cpu-exec.c:1065
cpu_exec cpu-exec.c:1091
tcg_cpu_exec tcg-accel-ops.c:78
mttcg_cpu_thread_fn tcg-accel-ops-mttcg.c:95
qemu_thread_start qemu-thread-posix.c:541
```

### Expected Behavior

There should be no segfault

### xemu Version

Debug build of 8.10, building at `5896b9dc91d2b8b94b2b30570e1e329b161c1453` for the trace

Also reproduced with 
```
Version:      0.8.10
Branch:       master
Commit:       5896b9dc91d2b8b94b2b30570e1e329b161c1453
Date:         Wed Jan 15 10:11:18 UTC 2025
```

and
```
Version:      0.7.85
Branch:       master
Commit:       065c74a00fe402f65147e9b0d1a1eeac1b4b609f
Date:         Mon Mar  6 21:06:33 UTC 2023
```

### System Information

```
CPU:          Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
OS Platform:  Linux
OS Version:   Ubuntu 24.04.1 LTS
Manufacturer: Mesa
GPU Model:    NV134
Driver:       4.3 (Core Profile) Mesa 24.0.9-0ubuntu0.3
Shader:       4.30
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mborgerson**
Fixes #1881

### CODE REVIEW

File: hw/xbox/nv2a/pgraph/vk/surface.c [hunk 1]
```diff
@@ -122,17 +122,29 @@ static void memcpy_image(void *dst, void const *src, int dst_stride,
     }
 }
 
-void pgraph_vk_download_surfaces_in_range_if_dirty(PGRAPHState *pg, hwaddr start, hwaddr size)
+static bool check_surface_overlaps_range(const SurfaceBinding *surface,
```
Comment (abaire) [inline hw/xbox/nv2a/pgraph/vk/surface.c:125]: Can these be moved to a shared file rather than duplicated across GL and VK?

Comment (mborgerson) [reply hw/xbox/nv2a/pgraph/vk/surface.c:125]: Not without more refactoring, which I'll defer for now
