### PR TITLE
nv2a: Ignore alpha when processing PVIDEO color keying

### LINKED ISSUE #2421: Constantine - Intro and cutscenes play audio but not video.
### Title

https://xemu.app/titles/5343000f/#Constantine

### Bug Description

Intro and cutscenes play audio, but won't show video; menus and gameplay show and run just fine.

Steps to reproduce:
Load the game
Watch loading screen
*intro sequence plays audio but not video*
Load into main menu
Start game
*loading screen shows as intended*
*level cutscene plays audio but not video*
*gameplay works as intended*

### Expected Behavior

An intro sequence showing many company logos and cutscenes at the start of levels are expected to play video and sound.

### xemu Version

0.8.98

### System Information

OS: Windows 11
Processor: Ryzen 5 5600X 3.7ghz
Graphics card: NVIDIA RTX2060 6gb
Graphics Drivers: GeForce Game Ready Version 581.29

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by abaire**
Discards the alpha value passed to the color key register, matching tested hardware behavior.

Fixes #2421

Tests: https://github.com/abaire/nxdk_pgraph_tests/blob/c64f5af5f7c3a890f1a00a927c6b72c2656ea025/src/tests/pvideo_tests.cpp#L761

Note: PVIDEO tests do not produce artifacts so they must be compared manually against HW. I have verified that they are identical for the subset of surface formats supported by xemu.

### CODE REVIEW

**Comment by Triticum0** [comment]
Fixed cold fear and constantine
constantine
xemu-2025-09-15-18-29-00

cold fear 
xemu-2025-09-15-18-29-24

**Comment by Triticum0** [comment]
Doesn't fix kill switch regression

File: hw/xbox/nv2a/pgraph/vk/display.c [hunk 1]
```diff
@@ -849,10 +849,8 @@ static PvideoState get_pvideo_state(PGRAPHState *pg)
     state.color_key_enabled =
         GET_MASK(d->pvideo.regs[NV_PVIDEO_FORMAT], NV_PVIDEO_FORMAT_DISPLAY);
 
-    // TODO: Verify that masking off the top byte is correct.
-    // SeaBlade sets a color key of 0x80000000 but the texture passed into the
-    // shader is cleared to 0 alpha.
-    state.color_key = d->pvideo.regs[NV_PVIDEO_COLOR_KEY] & 0xFFFFFF;
+    // Note: PVIDEO color keying ignores alpha.
+    state.color_key = d->pvideo.regs[NV_PVIDEO_COLOR_KEY] & 0xFFFFF;
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/vk/display.c]: 20 bit mask intentional?

Comment (abaire) [reply hw/xbox/nv2a/pgraph/vk/display.c]: Nope, good catch, fixed.

**Comment by antoniodesousa** [comment]
> Doesn't fix kill switch regression

All FMV cutscenes render perfect for me on both OpenGL and Vulkan.

xemu-2025-09-15-23-00-11
xemu-2025-09-15-23-11-26
xemu-2025-09-15-23-11-38
xemu-2025-09-15-23-11-45

**Comment by abaire** [comment]
I'd assume that Kill Switch is a different problem and should be covered by #1226. 

@antoniodesousa maybe you can add your system info there so we can see if it differs from @Triticum0

File: hw/xbox/nv2a/pgraph/vk/glsl.h [hunk 2]
```diff
@@ -165,10 +165,17 @@ void uniform2f(ShaderUniformLayout *layout, int idx, float v0, float v1)
 }
 
 static inline
-void uniform4f(ShaderUniformLayout *layout, int idx, float v0, float v1, float v2, float v3)
+    void uniform3f(ShaderUniformLayout *layout, int idx, float v0, float v1, float v2)
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/vk/glsl.h]: nit: prototype indentation (and below)

File: hw/xbox/nv2a/pgraph/pgraph.c [hunk 3]
```diff
@@ -3063,7 +3063,7 @@ void pgraph_get_clear_color(PGRAPHState *pg, float rgba[4])
         *b = 1.0f;
         fprintf(stderr, "CLEAR_SURFACE for color_format 0x%x unsupported",
                 pg->surface_shape.color_format);
-        assert(false);
+        assert(!"CLEAR_SURFACE not supported for selected surface format");
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/pgraph.c]: Unrelated?

File: hw/xbox/nv2a/pgraph/pgraph.c [hunk 4]
```diff
@@ -3077,7 +3077,7 @@ void pgraph_get_clear_color(PGRAPHState *pg, float rgba[4])
     case NV097_SET_SURFACE_FORMAT_COLOR_LE_X1A7R8G8B8_Z1A7R8G8B8:
     case NV097_SET_SURFACE_FORMAT_COLOR_LE_X1A7R8G8B8_O1A7R8G8B8:
         *a = ((clear_color >> 24) & 0x7F) / 127.0f;
-        assert(false); /* Untested */
+        assert(!"CLEAR_SURFACE handling for LE_X1A7R8G8B8_Z1A7R8G8B8 and LE_X1A7R8G8B8_O1A7R8G8B8 is untested"); /* Untested */
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/pgraph.c]: Unrelated?

File: hw/xbox/nv2a/pgraph/pgraph.c (hunk 3 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/pgraph.c]: Removed.

File: hw/xbox/nv2a/pgraph/vk/glsl.h (hunk 2 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/vk/glsl.h]: Fixed

File: hw/xbox/nv2a/pgraph/pgraph.c (hunk 4 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/pgraph.c]: Fixed

**Comment by mborgerson** [comment]
Thanks!

**Comment by Florin9doi** [comment]
This PR also fixed the DVD playback. Only the OSD was visible before
