### PR TITLE
nv2a: Fix oFog write behavior with non-x destination masks.

### LINKED ISSUE #978: Vertex shader `_in` expansion leads to incorrect behavior in `MOV` w/ a mask that does not include `x`
### Bug Description

While looking into fog behavior, I discovered that `MOV(oFog,yw, c[108].yw);` does not result in the same behavior as `oFog.yw = c[108].yw` (which is the intent and HW behavior).

`vec4 _in(vec2 v) { return v.xyyy; }` causes the MOV to be interpreted as `oFog.yw = c[108].ww` since the `y` is erroneously moved to the `x` component of the expanded vector and the `w` is used for the rest of the values.

### Expected Behavior

The values need to be expanded in a manner consistent with the source mask. In this particular case, `yyww` or `yyyw` would've worked.

### xemu Version

Based on the [git blame](https://github.com/mborgerson/xemu/blame/0cdcdde70c13f6cf3ed09aca29185ed790b22485/hw/xbox/nv2a/vsh.c#L617), this affects all version of xemu since the code came over from the xqemu fork

### System Information

n/a this bug is system independent.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by abaire**
Fixes #978 

Modifies the write masking behavior to fit the expansion done by `_in` and removes the need for the (slightly erroneous) fix made in #677.

The original tests were insufficient to detect this case since it wasn't straightforward to get Cg to produce the necessary code, the tests now use nv2a assembly directly.

[Expanded tests, the vec4 ones are the ones of interest](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/fog_tests.cpp)
[Updated HW results](https://github.com/abaire/nxdk_pgraph_tests_golden_results/wiki/Results-Fog_coord_vec4)

### CODE REVIEW

File: hw/xbox/nv2a/vsh.c [hunk 1]
```diff
@@ -436,24 +456,10 @@ static MString* decode_opcode(const uint32_t *shader_token,
         }
 
         int write_mask = vsh_get_field(shader_token, FLD_OUT_O_MASK);
-        mstring_append(ret, mask_str[write_mask]);
+        const char *write_mask_str = write_fog_register ? fog_mask_str[write_mask] : mask_str[write_mask];
```
Comment (PatrickvL) [inline hw/xbox/nv2a/vsh.c:459]: If a slightly different ordering of the rest after X is acceptable, this could also be done without the fog table by indexing the regular mask table with mask_index, but for fog first assert that zero won't appear in mask_index and shift it left while the X bit is not set.

Comment (abaire) [reply hw/xbox/nv2a/vsh.c:459]: Not sure I'm following. There are a lot of ways that this could be done, a lookup table (that's tiny and running on modern machines with tons of RAM) seems preferable to doing any sort of looping.
