### PR TITLE
pgraph: Takes pitch into account when converting YUV textures.

### LINKED ISSUE #153: XMV videos in Conan cause game to crash
Game will crash even with the addition of audio to xemu. replacing the *.xmv with dummy files will let you get into game.

No error is dumped to the log at crash.

### LINKED ISSUE #360: The Wild Rings: Crash upon loading
### Title Information

https://xemu.app/titles/4d530048/#The-Wild-Rings

### Bug Description

xemu crashes upon starting this title.

Steps to reproduce this issue:
1. Load game

### Expected Behavior

xemu should not crash.

### Version

* Version: a7f3f8f21221174efb65fdc0b8f7e2dd234c7412
* Last-known Working: N/A

### System Information

os_platform: Windows
os_version: Windows
cpu: Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
gl_vendor: NVIDIA Corporation
gl_renderer: Quadro P5000/PCIe/SSE2
gl_version: 4.0.0 NVIDIA 457.30
gl_shading_language_version: 4.00 NVIDIA via Cg compiler

### LINKED ISSUE #406: Operation Flashpoint: Segfault on Windows/NVIDIA
### Title Information

* https://xemu.app/titles/434d005a/#Operation-Flashpoint-Elite

### Bug Description
Steps to reproduce this issue:

1. Start game in Windows/NVIDIA GPU combination
2. It crashes after splash screens.

Using same ISO I was able to get to the menu (and overall play the game without problems) using Linux/INTEL GPU. To get the game running on Windows/NVIDIA it is possible to modify the iso and "nullify" game videos (just replace them with empty files). Those videos are playing in the menu (right before the crash) and it is most likely related to this problem.

### Expected Behavior
Videos are played without problem. Main menu works and you can reach the game.

### Version
https://github.com/mborgerson/xemu/releases/tag/build-202107110629

### Additional Context
There is nothing noted in logs. I tried to run debug release on Windows with GDB to see anything related. I'm attaching backtrace on segfault.

```
Thread 26 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 13116.0x22dc]
0x000000006c0e31e0 in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
(gdb) bt
#0  0x000000006c0e31e0 in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#1  0x000000006c0e2e50 in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#2  0x000000006bffd0a9 in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#3  0x000000006bffc5db in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#4  0x000000006bffc95f in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#5  0x000000006c014eb8 in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#6  0x000000006c0155fd in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#7  0x000000006c0b8a4e in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#8  0x000000006c0b8d8f in nvoglv64!DrvPresentBuffers () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#9  0x000000006bbfd4f3 in ?? () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#10 0x000000006bd04421 in ?? () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#11 0x000000006bd085f0 in ?? () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#12 0x000000006bd093b1 in ?? () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#13 0x000000006bd142b8 in ?? () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#14 0x000000006bbac035 in ?? () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#15 0x000000006bd28e70 in ?? () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#16 0x000000006bd28c20 in ?? () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#17 0x000000006bf9c8db in nvoglv64!DrvValidateVersion () from C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdi.inf_amd64_762029bf7d133519\nvoglv64.dll
#18 0x00007fffe99a7034 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\System32\kernel32.dll
#19 0x00007fffea602651 in ntdll!RtlUserThreadStart () from C:\WINDOWS\SYSTEM32\ntdll.dll
#20 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

I have checked all threads using `threads apply all bt`, but nothing related is present in there - no reference to any line in xemu itself.

### LINKED ISSUE #511: Incorrect video rendering in pre-menu FMV
### Title

https://xemu.app/titles/4541007e/#Tiger-Woods-PGA-Tour-06
https://xemu.app/titles/4541003a/#Tiger-Woods-PGA-Tour-2004
NTSC

### Bug Description

Graphical corruption in pre-menu video plaback.

The FMV is rendered on the top part of the screen with a hall of mirrors effect in the lower half (see screenshot). The problem persists throughout the video playback but is resolved at the menu screen, at which point the game appears to be playable.

Screenshot_20211029_205250

### Expected Behavior

The video should play back without corruption

### xemu Version

Version: 0.6.1-27-g42f8873b23
Branch:  master
Commit:  42f8873b23b0f76dca4a7c15c078201263b0464c
Date:    Sat Oct 30 03:42:42 AM UTC 2021

### System Information

OS: Kubuntu 21.04 - 5.11.0-38-generic
CPU: Core i7-6700K @ 4GHz
GPU: NVIDIA GeForce GTX 1070
GPU Driver: 4.6.0 NVIDIA 470.74

### Additional Context

_No response_

### LINKED ISSUE #535: There are some game that crash on window's during FMV's for unknown reasons
### Title Affected

https://xemu.app/titles/55530056/#AND-1-Streetball Fixed
https://xemu.app/titles/544d0008/#Conan Fixed *1
https://xemu.app/titles/41590004/#Dreamfall-The-Longest-Journey
https://xemu.app/titles/4d570022/#Gauntlet-Seven-Sorrows Fixed *1
https://xemu.app/titles/454d000a/#Mashed-Drive-to-Survive Fixed *1
https://xemu.app/titles/4d570038/#MLB-SlugFest-2006 Fixed
https://xemu.app/titles/434d005a/#Operation-Flashpoint-Elite Fixed *1
https://xemu.app/titles/4343000c/#Robin-Hood-Defender-of-the-Crown Fixed *1
https://xemu.app/titles/53430007/#Rolling Fixed *1
https://xemu.app/titles/4d530048/#The-Wild-Rings Fixed
https://xemu.app/titles/4541003a/#Tiger-Woods-PGA-Tour-2004 Fixed
https://xemu.app/titles/45410054/#Tiger-Woods-PGA-Tour-2005 Fixed
https://xemu.app/titles/4541007e/#Tiger-Woods-PGA-Tour-06 Fixed
https://xemu.app/titles/454100a4/#Tiger-Woods-PGA-Tour-07 Fixed
https://xemu.app/titles/43430014/#Without-Warning Fixed *1
https://xemu.app/titles/50430001/#Xyanide Fixed *1
### Bug Description

some games on windows crash with no assertion when trying to load FVM's This doesn't affect linux, where all game manage to progress past intro or the opening cut-screen.

Steps to reproduce this issue:
1.Insert disk
2.Go through FMV's  
3.game crashes with no assertion

### Expected Behavior

The FMV should display

### xemu Version

Version: 0.6.2
Branch: master
Commit: bbcd576
Date: Sat Oct 30 23:09:11 UTC 2021
Last-known Working: Unknown

### System Information

Field | Value
-- | --
OS | Windows 10 
CPU | AMD A6-5200 @ 2.0GHz
Graphics Device | AMD Radeon HD 8400 / R3 Series
Graphics Driver | Drivers: 4.0.13596 Core Profile Context 20.10.35.02 27.20.1034.6

### Additional Context
*1=Games tested by John God Games
Thank to John God Games for testing the majority of these games on windows you can find the game-play on his channel
Channel : https://www.youtube.com/channel/UC993yJ3ET5aFc6cRyukofjQ

### PR DESCRIPTION
**Pull request by abaire**
Fixes handling of YUV texture conversion to take source pitch into account and to use the row length of the converted texture instead of the original source.

Fixes #511 
Fixes #535 
Fixes #406 (confident of this one based on the stack trace, which matches the behavior I observed)

Fixes #153 (@Triticum0 )
Fixes #360 (@Triticum0 )

### CODE REVIEW

File: hw/xbox/nv2a/pgraph.c [hunk 1]
```diff
@@ -6439,14 +6439,12 @@ static void upload_gl_texture(GLenum gl_target,
...
         assert(s.pitch % f.bytes_per_pixel == 0);
-        glPixelStorei(GL_UNPACK_ROW_LENGTH,
-                      s.pitch / f.bytes_per_pixel);
 
         uint8_t *converted = convert_texture_data(s, texture_data,
                                                   palette_data,
                                                   s.width, s.height, 1,
                                                   s.pitch, 0);
-
+        glPixelStorei(GL_UNPACK_ROW_LENGTH, converted ? 0 : s.pitch / f.bytes_per_pixel);
```
Comment (abaire) [inline hw/xbox/nv2a/pgraph.c:6447]: I believe this line fixes #535 (by preventing the driver from being instructed to read way past the end of the converted texture buffer for large pitch values).

File: hw/xbox/nv2a/pgraph.c [hunk 2]
```diff
@@ -6386,10 +6386,10 @@ static uint8_t* convert_texture_data(const TextureShape s,
         // FIXME: only valid if control0 register allows for colorspace conversion
         uint8_t* converted_data = (uint8_t*)g_malloc(width * height * 4);
         int x, y;
+        uint8_t* pixel = converted_data;
         for (y = 0; y < height; y++) {
-            const uint8_t* line = &data[y * s.width * 2];
-            for (x = 0; x < width; x++) {
-                uint8_t* pixel = &converted_data[(y * s.width + x) * 4];
+            const uint8_t* line = &data[y * row_pitch * depth];
```
Comment (abaire) [inline hw/xbox/nv2a/pgraph.c:6391]: This should fix #511, assuming the source data is always packed.

Comment (Triticum0) [reply hw/xbox/nv2a/pgraph.c:6391]: Also should fix issues #153 and #40

File: hw/xbox/nv2a/pgraph.c (hunk 1 above)
Comment (Triticum0) [reply hw/xbox/nv2a/pgraph.c:6447]: Also should fix issues #153 and #406

Comment (abaire) [reply hw/xbox/nv2a/pgraph.c:6447]: Thanks for the info! Updated the comment to close them if this is merged.

Comment (Triticum0) [reply hw/xbox/nv2a/pgraph.c:6447]: Simi retested Operation Flashpoint : Elite  on windows but he said playback speed issues
> I can confirm video playback works now and game doesn't crash. But playback speed is really slow (like 0.5 FPS). I'll check the performance on better system. But I was able to run this without problems on Linux on integrated GPU.

Comment (Triticum0) [reply hw/xbox/nv2a/pgraph.c:6447]: also forgot it should fix #360

Comment (simi) [reply hw/xbox/nv2a/pgraph.c:6447]: I did another testing round (Operation Flashpoint: Elite game) on gaming PC (GTX 1070) using release (not debug) build. It works well, menu is running around 25 FPS (with video overlay). Playing just fullscreen video (when idle in menu) works well as with 25 FPS.

I can't compare to real hardware. But this seems ok to me.

Comment (Triticum0) [reply hw/xbox/nv2a/pgraph.c:6447]: Great, thanks for retesting.

**Comment by mborgerson** [comment]
Thanks!

**Comment by simi** [comment]
:muscle: :tada:
