### PR TITLE
nv2a: Invalidate GL textures after surface blit

### LINKED ISSUE #786: Splinter cell double agent: steam heat waves effect not handled correctly without goggles
### Title

https://xemu.app/titles/5553005e/#Tom-Clancy-s-Splinter-Cell-Double-Agent

### Bug Description

RE-tested on master:

https://user-images.githubusercontent.com/30447649/159268322-1639ca0b-3b90-4500-859a-4273d7265235.mp4

WHere is happens:
Level name: Iceland, first part, second part
kinshasa, second part beginning
sea of okosth, first part oging through a fire camp

### Expected Behavior

Steam waves should not cause a blue screen

### xemu Version

xemu_version: 0.6.2-88-g6e1969001e

### System Information

Manjaro Linux 
i7-10700 4.80GHz
GTX 970 STRIX 4GB VRAM
Nvidia driver 510.54 - CUDA Version 11.6

### PR DESCRIPTION
**Pull request by abaire**
Fixes #786 after a change to PR #835 prevented the fix from working (but allowed tests to pass). 

The original code in #835 worked because it over-aggressively forced the texture bindings to be regenerated, when this was scaled back in code review, the fix was left in a state where the stale texture binding was still being used, even though the surface binding (for the same hwaddr) was correctly updated.

### CODE REVIEW

File: hw/xbox/nv2a/pgraph.c [hunk 1]
```diff
@@ -397,7 +397,7 @@ static void pgraph_download_surface_data_to_buffer(NV2AState *d,
                                                    uint8_t *pixels);
 static void pgraph_upload_surface_data(NV2AState *d, SurfaceBinding *surface, bool force);
 static bool pgraph_check_surface_compatibility(SurfaceBinding *s1, SurfaceBinding *s2, bool strict);
-static bool pgraph_check_surface_to_texture_compatibility(SurfaceBinding *surface, TextureShape *shape);
+static bool pgraph_check_surface_to_texture_compatibility(const SurfaceBinding *surface, const TextureShape *shape);
```
Comment (abaire) [inline hw/xbox/nv2a/pgraph.c:400]: I can split this into a separate PR if desired; having these mutable made me worry that the check might've been doing something interesting when I was trying to pin down the regression from the original PR.

Comment (mborgerson) [reply hw/xbox/nv2a/pgraph.c:400]: No worries

File: hw/xbox/nv2a/pgraph.c [hunk 2]
```diff
@@ -887,7 +887,9 @@ static void pgraph_image_blit(NV2AState *d)
             surf_dest->download_pending = false;
             surf_dest->draw_dirty = false;
         }
+        surf_dest->draw_time = pg->draw_time;
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph.c]: How about we set a surface's draw time in the upload handler instead

Comment (abaire) [reply hw/xbox/nv2a/pgraph.c]: Done.
