### PR TITLE
nv2a: Use rounded values for alpha testing

### LINKED ISSUE #1912: Handling of NV097_SET_ALPHA_FUNC is incorrect for float values that match the reference.
### Bug Description

See deltas here:
https://abaire.github.io/xemu-nxdk_pgraph_tests_results/compare/xemu-0.8.20-master-3bdb9e7fd4d6c9f5adec0543f1679d2943a0d092/Linux_x86_64/gl_NVIDIA_Corporation_NVIDIA_GeForce_GTX_1070-PCIe-SSE2%3Agslv_4.00_NVIDIA_via_Cg_compiler/Alpha_func.html

The behavior is close to correct but fails for interpolated values that should match the reference value. 

This could potentially cause missing rasters or visible rasters that should be culled.

### Expected Behavior

xemu output should [match HW results](https://abaire.github.io/nxdk_pgraph_tests_golden_results/results/Alpha_func/index.html)

### xemu Version

xemu-0.8.20-master-3bdb9e7fd4d6c9f5adec0543f1679d2943a0d092

### System Information

xemu_version: 0.8.20
xemu_branch: master
xemu_commit: 3bdb9e7fd4d6c9f5adec0543f1679d2943a0d092
xemu_date: Sun Feb 16 00:00:03 UTC 2025
CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
OS_Version: Ubuntu 24.04.2 LTS
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: NVIDIA GeForce GTX 1070/PCIe/SSE2
GL_VERSION: 4.0.0 NVIDIA 570.86.15
GL_SHADING_LANGUAGE_VERSION: 4.00 NVIDIA via Cg compiler

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by abaire**
Fixes #1912

[Tests](https://github.com/abaire/nxdk_pgraph_tests/blob/fd47469ad52548a5b24aebd1630532b0d436e07b/src/tests/alpha_func_tests.cpp#L1)

[HW results](https://abaire.github.io/nxdk_pgraph_tests_golden_results/results/Alpha_func/index.html)
[Pre-CL results](https://abaire.github.io/xemu-nxdk_pgraph_tests_results/compare/xemu-0.8.20-master-3bdb9e7fd4d6c9f5adec0543f1679d2943a0d092/Linux_x86_64/gl_NVIDIA_Corporation_NVIDIA_GeForce_GTX_1070-PCIe-SSE2%3Agslv_4.00_NVIDIA_via_Cg_compiler/Alpha_func.html)

CL results can be found [here](https://github.com/abaire/xemu-dev_pgraph_test_results/tree/fix/1912_alpha_test_should_use_rounded_values/results/xemu-0.8.20-1-g60c8e4e513-fix_1912_alpha_test_should_use_rounded_values-60c8e4e5139511672c682a4d54c7ab76ace87452/Darwin_arm64/gl_Apple_Apple_M3_Max/gslv_4.10/Alpha_func)

### CODE REVIEW

File: hw/xbox/nv2a/pgraph/gl/shaders.c [hunk 1]
```diff
@@ -712,9 +712,9 @@ static void shader_update_constants(PGRAPHState *pg, ShaderBinding *binding,
         }
     }
     if (binding->alpha_ref_loc != -1) {
-        float alpha_ref = GET_MASK(pgraph_reg_r(pg, NV_PGRAPH_CONTROL_0),
-                                   NV_PGRAPH_CONTROL_0_ALPHAREF) / 255.0;
-        glUniform1f(binding->alpha_ref_loc, alpha_ref);
+        int alpha_ref = GET_MASK(pgraph_reg_r(pg, NV_PGRAPH_CONTROL_0),
+                                   NV_PGRAPH_CONTROL_0_ALPHAREF);
+        glUniform1i(binding->alpha_ref_loc, alpha_ref);
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/gl/shaders.c:717]: Please also update the Vulkan renderer (vk/shaders.c). The change should be nearly identical

Comment (abaire) [reply hw/xbox/nv2a/pgraph/gl/shaders.c:717]: Done, at the moment I don't have any way to test Vulkan, but it at least compiles.

Comment (mborgerson) [reply hw/xbox/nv2a/pgraph/gl/shaders.c:717]: Appears to work! Thanks
