### PR TITLE
nv2a: Adjust NaN handling for fog coordinate and colors to be similar to HW

### LINKED ISSUE #365: Blackened Texture Issues and Documentation
### Title Information

* Titles: Otogi FS-002 [46530002]
* https://xemu.app/titles/46530002/

* Titles: Otogi: Hyakki Toubatsu Emaki FS-004 [46530004]
* https://xemu.app/titles/46530004/

### Bug Description

Otogi 1: The only major issue I have encountered for the first game is a failure to load the character/weapon textures properly. Instead Raikoh has some sort of shadow texture over their model.

Steps to reproduce this issue:
1. Start the game.
2. Skip any cutscenes.
3. Start any stage and observe the main character. 

https://cdn.discordapp.com/attachments/680221390359888154/856388676602298368/Otogi_1_1.png
https://cdn.discordapp.com/attachments/680221390359888154/856388690561204244/Otogi_1_2.png

Otogi 2: The second game has more issues, starting with major slowdown in nearly every part of the game. The menus, saving, loading, all of it is locked at 5 fps. The only thing unaffected is the stage gameplay, which has normal slowdown similar to the first game.

The other major issue is some stages not loading environment textures properly, resulting in the entire level being covered in shadow textures. This can be observed in the starting stage...
https://cdn.discordapp.com/attachments/680221390359888154/856389461860810762/Otogi_2_1.png

However, some stages load properly...
https://cdn.discordapp.com/attachments/680221390359888154/856389890529558548/Otogi_2_2.png
So I will be doing further testing to see which stages load and which don't to find out if there is any pattern. Also note that the character/weapon texture load fail from the first game has persisted.

Steps to reproduce these issues:
1. Start a new game, you will have to go through game, sound, and controls settings, then save before beginning gameplay.
2. Note the slowdown to 5 fps during these menus and the save process.
3. Skip any cutscenes.
4. Observe the first stage.

### Expected Behavior

For Otogi 1, Raikoh and his weapon(s) should obviously have their textures.

For Otogi 2, there shouldn't be any slowdown in any of the menus. The menus in Otogi 1 worked fine, and I am fairly certain the games use the same engine, so I have no idea what could have been changed between games to be causing this problem. As for the missing textures, obviously the stages should all have their textures. I am not sure why some stages work and others don't, and plan to investigate further.

### Version

* Version: v0.5.4-7-ga7f3f8f212
* Last-known Working: Unknown

### System Information

| Field | Value |
|-------|-------|
| OS			| Windows 10 Pro			| 
| CPU			| AMD FX(tm)-8350 Eight-Core Processor			| 
| Graphics Device	| Radeon RX 580		| 
| Graphics Driver	| Radeon 21.4.1		|

### LINKED ISSUE #1026: Thousand Land | Not Rendering Correctly
### Title

https://xemu.app/titles/46530003/#Thousand-Land

### Bug Description

Once you reach in game, everything is rendering in white, you can hardly tell what is going on

xemu-2022-06-04-18-12-44
xemu-2022-06-04-18-13-05

### Expected Behavior

The ingame graphics should be rendering correctly like this:

thousandland4

### xemu Version

0.7.28

### System Information

Windows 11
Intel i7-10875H
RTX 2080 8GB
512.95

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by abaire**
Resurrecting #913 and incorporating some of the comments from #1780 in the hopes that:

1) This approach will work across different GPU manufacturers (testing needed, it works for M3 mac and my old NVIDIA 1070)
2) That the handful of fog nan mishandles that have been identified are the only places where NaN handling is important in practice so the perf hit of patching up NaNs can be limited to once per vertex instead of having to run on all attribs.

I suspect that the MUL zero handling fix that was added in #1045 may already be preventing/masking some issues.

[HW exceptional fog tests](https://abaire.github.io/nxdk_pgraph_tests_golden_results/results/Fog_exceptional_value/index.html)
[PR test results](https://abaire.github.io/xemu-dev_pgraph_test_results/fix_nan_fog/index.html)

This PR does not fix all issues with the exceptional fog tests, but it does fix the ones that seem to matter for Otogi. I have not fully reversed how fog params are utilized so I think the pgraph tests may be generating cases that would never be triggered by D3D.

(Probably) Fixes https://github.com/xemu-project/xemu/issues/365 by forcing treatment of NaN fog values generated in the vertex shader to follow the same pattern as HW.
Reportedly fixes #1026 as well

### CODE REVIEW

**Comment by Triticum0** [comment]
Thank abaire. You been working really hard with the pr's keep up the good work.

**Comment by viniciusol263** [comment]
Otogi 1 working perfectly here on my rig: RTX 2070 SUPER

**Comment by Enkak** [comment]
Tried 3 games from the same company, From Software, that had the issue of no textures. All 3 working good/normal here with an old GPU NVIDIA GTX 765M regarding that issue with this PR:
Otogi 1
Otogi 2
Thousand Land

**Comment by Fabxx** [comment]
Tested on splinter cell double agent and pandora tomorrow, no regressions to report.

**Comment by Triticum0** [comment]
Tested all game on the last pr + #472, #112, #1052, and #1096. Other issues had no changes with only game that had issues was Pro Cast: Sports Fishing Game so that will need to be looked in further.
Masters:
xemu-2025-04-10-13-20-06

PR 
xemu-2025-04-10-13-17-24

**Comment by real-guilty** [comment]
I've been trying to build this in MSYS2 for the last couple hours, but even after pulling _all_ the needed dependencies, CMake and Vulkan has done everything it can to prevent me from testing it for myself. They should have split the Vulkan backend into its own version of xemu--implementing it this way has been nothing but problems. For the third or fourth time now, I'm giving up on this. Hopefully this is merged or you release this yourself at some point.

**Comment by abaire** [comment]
Any reason the build artifacts attached to the PR don't work for you? There are windows builds.

**Comment by real-guilty** [comment]
> Any reason the build artifacts attached to the PR don't work for you? There are windows builds.

I am Git-illiterate. I found the artifacts though and am running O1 now. Looks great--0.8.47 and I can see everything. Will run some stages--hell, maybe speedrun it--then go through O2 just to be another name that can confirm the fix.

You wouldn't happen to also be wise on the audio utilization issues I've reported, would you? "Clouded Moon" and "Inner Sanctum" for O1, and "Golden Sea" for O2.

**Comment by mborgerson** [comment]
@real-guilty 

> I've been trying to build this in MSYS2 for the last couple hours, but even after pulling all the needed dependencies, CMake and Vulkan has done everything it can to prevent me from testing it for myself. They should have split the Vulkan backend into its own version of xemu--implementing it this way has been nothing but problems. For the third or fourth time now, I'm giving up on this. Hopefully this is merged or you release this yourself at some point.

Users are recommend to use the release build or download artifacts from GitHub instead of building from source. I'm not sure what issues you're having with building from source, but it sounds like you didn't follow [the directions](https://xemu.app/docs/dev/building-from-source/).

> You wouldn't happen to also be wise on the audio utilization issues I've reported, would you? "Clouded Moon" and "Inner Sanctum" for O1, and "Golden Sea" for O2.

Let's keep the conversation on this issue focused on the matter at hand and not on various other Otogi issues. General chat is welcome on the xemu Discord server.

**Comment by abaire** [comment]
Thanks to `Sinful` on Discord: the current fix does not work on SteamDeck in Windows

```
        "{\n"
        "  bvec4 nans = isnan(src);\n"
        "  if (!any(nans)) {\n"
        "    return src;\n"
        "  }\n"
        "  return mix(src, sign(floatBitsToInt(src)), nans);\n"
        "}
```

**Comment by abaire** [comment]
With `Sinful`'s help I was able to get the fix working on the Steam Deck. Will need to be re-tested on NVIDIA HW as well to make sure it hasn't regressed.

At the moment I can confirm that it works on Darwin/M3 (but the default NaN handling on Darwin/M3 already worked without this PR).

**Comment by Triticum0** [comment]
I'll test it. post results in 20 mins

**Comment by viniciusol263** [comment]
image
on RTX 2070 SUPER

**Comment by Triticum0** [comment]
You still need to have a look at Pro Cast: Sports Fishing Game  it still doesn't look correct

**Comment by Triticum0** [comment]
Here you go. GPU:3060 ti

Otogi 1
xemu-2025-04-15-23-26-36

Otogi 2
xemu-2025-04-15-23-27-34

Thousand Land
xemu-2025-04-15-23-29-32

Triggerman
xemu-2025-04-15-23-30-54


Pro Cast: Sports Fishing
xemu-2025-04-15-23-26-23

**Comment by abaire** [comment]
> You still need to have a look at Pro Cast: Sports Fishing Game it still doesn't look correct

@Triticum0 I'm assuming the issue there has some cause other than NaN fog. I've ordered the game and will investigate in the coming weeks. If there isn't already a GH issue specifically tracking the problem, can you create one?

**Comment by Triticum0** [comment]
Not sure if that necessary coldhex has the game and posted about it on previous pr https://github.com/xemu-project/xemu/pull/1780#issuecomment-2480620232 he mentioned why it occurred there

**Comment by Triticum0** [comment]
If that not helpful then i happy make an new issue tomorrow.

**Comment by abaire** [comment]
Unfortunately it seems that the fix that worked on my personal branch did not work after being re-applied here, working w/ `Sinful` to see if I can figure out why. Back to draft until then.

@Triticum0 let's add a new issue specific for Pro Cast, it'll require applying this fix to the color channels as well as fog

**Comment by abaire** [comment]
Turns out that the `floatBitsToInt` causes this to fail on AMD (at least on Steam Deck). Removed and added a comment for future investigation. We'll want to test this yet again on NVIDIA HW.

**Comment by viniciusol263** [comment]
Working on a RTX 2070 SUPER 
image

**Comment by abaire** [comment]
Something changed with macOS 15.4.1 such that `sign(nan)` appears to be returning 0 now. I think we can drop the sign check and just set all nan's to 1. It won't be exactly like the HW results since multiplying nan's by 0/practically 0 numbers returns 0, but it will match most of the cases, including Otogi.

**Comment by abaire** [comment]
Something changed with macOS 15.4.1 such that `sign(nan)` appears to be returning 0 now. I think we can drop the sign check and just set all nan's to 1. It won't be exactly like the HW results since multiplying nan's by 0/practically 0 numbers returns 0, but it will match most of the cases, including Otogi.

**Comment by abaire** [comment]
Verified working on Darwin, NVIDIA, and AMD (Steam Deck)

**Comment by Triticum0** [comment]
Glad it works now on all vendors. hopefully merged soon.

File: hw/xbox/nv2a/pgraph/glsl/vsh.c [hunk 1]
```diff
@@ -128,6 +128,21 @@ MString *pgraph_gen_vsh_glsl(const ShaderState *state, bool prefix_outputs)
...
+
+    mstring_append(
+        header,
+        "/* Converts the input to vec4, pads with last component */\n"
+        "vec4 _in(float v) { return vec4(v); }\n"
+        "vec4 _in(vec2 v) { return v.xyyy; }\n"
+        "vec4 _in(vec3 v) { return v.xyzz; }\n"
+        "vec4 _in(vec4 v) { return v.xyzw; }\n"
+        "\n"
+        "#define FixNaNClamped(src, mask) _FixNaNClamped(_in(src)).mask\n"
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/glsl/vsh.c]: * Seems like the `mask` parameter is unnecessary?
* Also the macro is only used in one place so it is probably redundant overall?

File: hw/xbox/nv2a/pgraph/glsl/vsh.c [hunk 2]
```diff
@@ -128,6 +128,21 @@ MString *pgraph_gen_vsh_glsl(const ShaderState *state, bool prefix_outputs)
...
+        "vec4 _FixNaNClamped(vec4 src)\n"
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/glsl/vsh.c]: What values are clamped here, to what bounds? A better name might be `NanToOne`, or something

File: hw/xbox/nv2a/pgraph/glsl/vsh.c (hunk 1 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/glsl/vsh.c]: It's buried in the comments, but after looking at coldhex's finding: https://github.com/xemu-project/xemu/pull/1780#issuecomment-2480620232 I think we should go back to applying this to colors as well. Wanted to discuss before I bothered to make the change.

We can drop the mask and just apply during the final assignment.

File: hw/xbox/nv2a/pgraph/glsl/vsh.c (hunk 2 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/glsl/vsh.c]: Sounds good, the name hasn't kept up with the evolution to work around implementation-specific issues.

**Comment by abaire** [comment]
Updated to resolve comments and expanded to cover color channels as discussed. 

This introduces some new/modified deltas versus hardware in lighting test results on Darwin/M3, but only in exceptional cases (e.g., infinite attenuation and spotlight falloff due to pathological values that I think cannot be generated by DirectX). The dev branch results page has been updated to demonstrate.

**Comment by Enkak** [comment]
Hi and just a quick question if this has been merged to master yet? 

I have the github artifact just for the Otogi games but since there were some updates to the PR just to check if maybe I missed the merging or if there's still some technical conflicts or issues to solve.

Cheers and thank you all for the hard work.

**Comment by abaire** [comment]
> Hi and just a quick question if this has been merged to master yet?

When it's merged this page will have a purple icon that says "Merged" instead of a green icon that says "Open".

**Comment by Enkak** [comment]
> > Hi and just a quick question if this has been merged to master yet?
> 
> When it's merged this page will have a purple icon that says "Merged" instead of a green icon that says "Open".

Ah I see. Many thanks for the clarification!

**Comment by Triticum0** [comment]
Tested Dinosaur Hunter with pr and doesn't seem to have any affect on issue #1622

**Comment by antoniodesousa** [comment]
I tested all the games that are known to have the black fog issue and they're all fixed in this PR. I also tested a bunch of other games and I didn't see any apparent regressions. Hopefully, the PR gets merged soon. I'm tired of using a custom build to play the Otogi games.

```
Version: 0.0.0
Branch: fix_nan_fog
Commit: d6b00e952f01a340be61081947cb326e4666c707
Date: Sat Apr 26 23:08:27 UTC 2025
CPU: AMD Ryzen 9 6900HX with Radeon Graphics        
OS Platform: Windows
OS Version: 24H2
Manufacturer: ATI Technologies Inc.
GPU Model: AMD Radeon RX 6600M
Driver: 4.0.0 Core Profile Context 25.5.1.250417
Shader: 4.60
```
xemu-2025-05-15-15-42-00
xemu-2025-05-15-15-47-15
xemu-2025-05-15-15-47-49
xemu-2025-05-15-15-49-58
xemu-2025-05-15-16-07-58

File: hw/xbox/nv2a/pgraph/glsl/vsh.c [hunk 3]
```diff
@@ -232,17 +240,17 @@ MString *pgraph_gen_vsh_glsl(const ShaderState *state, bool prefix_outputs)
             break;
         }
 
-        mstring_append(body, "  oFog.xyzw = vec4(fogFactor);\n");
+        mstring_append(body, "  oFog.xyzw = NaNToOne(vec4(fogFactor));\n");
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/glsl/vsh.c]: nit: `.xyzw` eliminated below but not here?

File: hw/xbox/nv2a/pgraph/glsl/vsh.c [hunk 4]
```diff
@@ -128,6 +128,14 @@ MString *pgraph_gen_vsh_glsl(const ShaderState *state, bool prefix_outputs)
             }
         }
     }
+
+    mstring_append(
+        header,
+        "vec4 NaNToOne(vec4 src)\n"
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/glsl/vsh.c]: nit: Let's just move this up to follow `clampAwayZeroInf` definition above

File: hw/xbox/nv2a/pgraph/glsl/vsh.c (hunk 3 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/glsl/vsh.c]: Done

File: hw/xbox/nv2a/pgraph/glsl/vsh.c (hunk 4 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/glsl/vsh.c]: Done

**Comment by mborgerson** [comment]
Thanks! Adjusted commit message to be more descriptive of the change

**Comment by cerroverb** [comment]
no fucking way this was actually finally fixed
