### PR TITLE
nv2a: Handle PGRAPH color keying

### LINKED ISSUE #713: nv2a 0x97 -> 0x0ae* (Unidentified) unhandled
### Title

https://xemu.app/titles/4d53006e
https://xemu.app/titles/4d5300d1
https://xemu.app/titles/53430007

### Bug Description

According to the debug output, 0x97 -> 0x0AE0 - 0x0AEC are unhandled.
I can't find any reference to this range in the NV20 nouveau sources, nor NV30-40.

The parameter of these calls has so far been observed as one of the following:
`0x0`

### Expected Behavior

The NV2A instructions 0x0AE0, 0x0AE4, 0x0AE8, and 0x0AEC should be handled.

### xemu Version

0.6.2-55-gcaf84884c4

### System Information

N/A

### Additional Context

_No response_

### LINKED ISSUE #1052: Eggo Mania Graphical issues
### Title

https://xemu.app/titles/4b420002/#Eggo-Mania

### Bug Description

There is a black border around some assets during the character selection and in-game.
xemu-2022-06-10-01-25-38
xemu-2022-06-10-01-25-51

### Expected Behavior

Should not happen

### xemu Version

Version: 0.7.29
Branch: master
Commit: https://github.com/mborgerson/xemu/commit/69dcbe9b3081ee51d1468b1b7777b8b930bfba6c
Date: Wed Jun 8 05:09:16 UTC 2022

### System Information

<html><body>

Field | Value
-- | --
OS | Windows 10
CPU | AMD Ryzen 5 2600 Six-Core Processo
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 512.95

</body>
</html>

### Additional Context

similar to #632
Here a renderdoc of character select menu : https://drive.google.com/file/d/1LAyvjDipsctKiYesgJrDgukyGu8nWgbh/view?usp=sharing

### LINKED ISSUE #1136: American Chopper Series Tree Glitch
### Title
https://xemu.app/titles/4156003d/#American-Chopper
https://xemu.app/titles/4156004f/#American-Chopper-2-Full-Throttle

### Bug Description

The trees don't render correctly simar to #1110
American Chopper Xemu:
Screenshot 2022-06-30 20-03-21
American-Chopper 2 Full-Throttle Xemu:
xemu-2022-06-24-13-41-52

### Expected Behavior
Screenshot 2022-06-30 19-59-31

Should look correct 

### xemu Version

Version: 0.7.55
Branch: master
Commit: https://github.com/mborgerson/xemu/commit/db389b15086753cb7b72e05b24af205baa742bc3
Date: Sun Jun 26 05:58:57 UTC 2022

### System Information

<html><body>

Field | Value
-- | --
OS | Windows 10
CPU | AMD Ryzen 5 2600 Six-Core Processo
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 512.95

</body>
</html>

### Additional Context

Here a renderdoc https://drive.google.com/file/d/1nRo4eqaHuuDMu7TOz2r2i8LGhQ31rQ64/view?usp=sharing

### LINKED ISSUE #1198: Square boarders around crowd in PAM Development games
### Title

https://xemu.app/titles/4d530035/#Top-Spin
https://xemu.app/titles/57450001/#Ultimate-Beach-Soccer

### Bug Description

The crowd have glitchy squares bordering around them affecting both games
Ultimate Beach Soccer:
xemu-2022-07-20-17-23-32

Top Spin:
xemu-2022-07-23-10-26-32

### Expected Behavior

https://youtu.be/tbx3iUc26kk?t=135
https://youtu.be/cE8zTppPTeY?t=176

### xemu Version

Version: 0.8.66
Branch: master
Commit: https://github.com/mborgerson/xemu/commit/248fc788c177e7b01ec1455b2005ee339332edbf
Date: Tue Jul 19 01:06:48 UTC 2022

### System Information

<html><body>

Field | Value
-- | --
OS | Windows 10
CPU | AMD Ryzen 5 2600 Six-Core Processor
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 512.95

</body>
</html>

### Additional Context

Renderdoc https://drive.google.com/file/d/18ui0cLYKjTQ4k4j1-lClrwCvvqrnN6bE/view?usp=sharing

[Ultimate Beach Soccer.log](https://github.com/user-attachments/files/20442853/Ultimate.Beach.Soccer.log)

### PR DESCRIPTION
**Pull request by abaire**
Fixes #713 
Fixes #1198 
Fixes #1136 
Fixes #1052

[Tests](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/color_key_tests.cpp)
[Results](https://abaire.github.io/xemu-dev_pgraph_test_results/fix_713_color_key/index.html)

### CODE REVIEW

**Comment by abaire** [comment]
Draft as I haven't run the regression tests or tested with Vulkan yet.

@Triticum0 can you check if this actually fixes the issues you linked to #713 when you have a chance?

**Comment by Triticum0** [comment]
### Fixed games
ameraican chopper 
xemu-2025-06-02-18-46-17

ameraican chopper 2
xemu-2025-06-02-18-46-27

Ultimate Beach Soccer
xemu-2025-06-02-18-47-39

Eggo Mania 
xemu-2025-06-02-21-13-11

Top spin
xemu-2025-06-02-21-28-56

Untested
Fable: The Lost Chapters
Forza Motorsport

Did you want a pgraph log for the games not fixed. also dont know what color keying used for fable: the lost chapters so couldn't really give a screenshot but I could give you a new  pgraph log.

**Comment by abaire** [comment]
> ### Fixed games

> Forza Motorsport #1065

Are you sure this fixes it? When I looked into that issue it seemed to be a problem with the way border colors are applied in xemu, which is definitely not addressed by this PR. Testing with this PR on macOS/M3 I still see the incorrect borders.


> Did you want a pgraph log for the games not fixed. also dont know what color keying used for fable: the lost chapters so couldn't really give a screenshot but I could give you a new pgraph log.

Yeah, the pgraph log will let us figure out if the games are actually using color keying or not (just specifying the color key color isn't enough to enable it, you also need to check the low 2 bits for the various TEXTURE_CONTROL0 commands).

**Comment by Triticum0** [comment]
Do I need this custom build with renderdoc enabled or can use this build with pgraph enabled in qemu terminal. I left pgraph log in issue listed earlier today

**Comment by Triticum0** [comment]
Seem the boards not present on vulkan render.
Opengl 
xemu-2025-06-02-19-20-30

Vulkan
xemu-2025-06-02-19-05-25

**Comment by Triticum0** [comment]
I forgot how to enable pgraph logging tried nv2a_pgraph_* with no luck. Does it only work with debug builds? I did take some early an left them here #713. I send some new ones once I get logging to work on this build.

**Comment by abaire** [comment]
> I forgot how to enable pgraph logging tried nv2a_pgraph_* with no luck. Does it only work with debug builds? I did take some early an left them here #713. I send some new ones once I get logging to work on this build.

I thought tracing worked on any build (see https://xemu.app/docs/dev/debug/guest/#runtime-usage-preferred ). We would only need traces for games that don't already have them where you're pretty sure that color keying matters (it'd at least have the `unhandled` message in a master build). If you've already attached traces we probably don't need new ones (e.g., I just used the one you added for Eggo Mania to figure out what I think is the issue there).

**Comment by Triticum0** [comment]
Tried to get a log for forza and rolling but don't know what actually caused key color to be unhandled in the games and performace with it on way too slow under 1fps  ingame. so not sure what I could do. Old rolling log are remove by github. So not sure what to do to find unhandled command to close the issue or will proper test case suffice. As if it a object type need to be rendered performace ingame too poor to actually play enough  to find what cause command to be hit. can only really test menus.

**Comment by abaire** [comment]
> d rolling but don't know what actually caused key color to be unhandled in the games and performace with it on way too slow under 1fps ingame. so not sure what I could do. Old rolling log are remove by github. So not sure what to do to find unhandled command to close the is

I don't think Forza has an issue with color keying.

I ended up ordering Rolling, so I'll eventually look into it, it's very possible that the issue there is not related to color keying either.

The reason I generally use my `work` branch for pgraph logging is to make use of https://github.com/abaire/xemu/tree/debug/toggle_pgraph_trace_with_f9 to avoid having to interact with the monitor while the framerate is tanking due to all the logging. It definitely is tricky if the issue only pops when a certain action is taken, it may require customizing the traces to reduce verbosity.


I just pushed an additional commit to this PR that I hope will address #1052 - can you check again when you have a chance?

**Comment by Triticum0** [comment]
I left Renderdoc on rolling issue if you not already look at it. Also Eggo mania is fixed with your pr
xemu-2025-06-02-21-13-11

xemu-2025-06-02-21-13-37

**Comment by Triticum0** [comment]
Also thought #1228 might be related but look at log and testing with the pr it seem not

File: hw/xbox/nv2a/pgraph/glsl/psh.c [hunk 1]
```diff
@@ -731,6 +738,21 @@ static void apply_convolution_filter(const struct PixelShader *ps, MString *vars
         "}\n", tex, tex, tex, tex, tex_remap, tex);
 }
 
+static void define_colorkey_comparator(MString *preflight)
+{
+    mstring_append(preflight,
```
Comment (abaire) [inline hw/xbox/nv2a/pgraph/glsl/psh.c]: I wonder if we should `// clang-format off` on long GLSL codegen lines. The introduced breaks make these much harder to read, in my opinion.

Comment (mborgerson) [reply hw/xbox/nv2a/pgraph/glsl/psh.c]: That would be fine

Comment (abaire) [reply hw/xbox/nv2a/pgraph/glsl/psh.c]: Cool, done.

File: hw/xbox/nv2a/pgraph/gl/shaders.c [hunk 2]
```diff
@@ -960,40 +982,41 @@ static bool test_shaders_dirty(PGRAPHState *pg)
...
-        CR_8(NV_PGRAPH_WINDOWCLIPX0) \
-        CR_8(NV_PGRAPH_WINDOWCLIPY0) \
-        CF(pg->primitive_mode, primitive_mode) \
-        CF(pg->surface_scale_factor, surface_scale_factor) \
-        CF(pg->compressed_attrs, compressed_attrs) \
-        CFA(pg->texture_matrix_enable, texture_matrix_enable)
-
-    #define CR_x(reg, x) CR_x__define(reg, x)
-    #define CF_x(type, src, name, x) CF_x__define(type, src, name, x)
+#define DIRTY_REGS                                        \
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/gl/shaders.c]: Please revert whitespace changes

File: hw/xbox/nv2a/pgraph/gl/shaders.c [hunk 3]
```diff
@@ -725,6 +737,16 @@ static void shader_update_constants(PGRAPHState *pg, ShaderBinding *binding,
         glUniform1i(binding->alpha_ref_loc, alpha_ref);
     }
 
+    for (i = 0; i < 4; ++i) {
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/gl/shaders.c]: Combine with below loop?

File: hw/xbox/nv2a/pgraph/vk/shaders.c [hunk 4]
```diff
@@ -490,7 +496,21 @@ static void shader_update_constants(PGRAPHState *pg, ShaderBinding *binding,
         uniform1i(&binding->fragment->uniforms, binding->alpha_ref_loc,
                          alpha_ref);
     }
-
+    if (binding->color_key_loc != -1) {
+        uint32_t color_key_colors[4] = {
+            pg->regs_[NV_PGRAPH_COLORKEYCOLOR0],
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/vk/shaders.c]: Prefer accessor `pgraph_reg_r`

File: hw/xbox/nv2a/pgraph/gl/shaders.c (hunk 2 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/gl/shaders.c]: This is all from git clang-format. Do you want this to be wrapped w/ clang-format off?

File: hw/xbox/nv2a/pgraph/glsl/psh.c [hunk 5]
```diff
@@ -174,6 +174,13 @@ enum PS_DOTMAPPING
     PS_DOTMAPPING_HILO_HEMISPHERE=     0x07L, // - * * *
 };
 
+enum PS_COLORKEYMODE {
+    COLOR_KEY_NONE = 0,
+    COLOR_KEY_KILL_ALPHA = (1 << 0),
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/glsl/psh.c]: nit: It's unusual to use bitshifts here if this field does not represent a bitmask. Suggest just using the digits 0..3

File: hw/xbox/nv2a/pgraph/shaders.c [hunk 6]
```diff
@@ -24,6 +24,14 @@
 #include "pgraph.h"
 #include "shaders.h"
 
+static bool color_format_ignores_alpha(unsigned int color_format)
+{
+    return color_format == NV097_SET_TEXTURE_FORMAT_COLOR_SZ_X1R5G5B5 ||
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/shaders.c]: What happens for other formats with fewer components?

File: hw/xbox/nv2a/pgraph/gl/shaders.c (hunk 3 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/gl/shaders.c]: Done

File: hw/xbox/nv2a/pgraph/vk/shaders.c (hunk 4 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/vk/shaders.c]: Done

File: hw/xbox/nv2a/pgraph/glsl/psh.c (hunk 5 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/glsl/psh.c]: Done, it was an artifact of discovering that "DISCARD" is not just a trivial combination of the two presumed bits.

File: hw/xbox/nv2a/pgraph/gl/shaders.c (hunk 2 above)
Comment (mborgerson) [reply hw/xbox/nv2a/pgraph/gl/shaders.c]: Nope, just prefer not to have the whitespace change here (it's difficult to see the addition from the format noise). We'll clang-format in a separate pass

File: hw/xbox/nv2a/pgraph/shaders.c (hunk 6 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/shaders.c]: Happy to TODO/FIXME it and deal with it when there's a usecase. It'd also be interesting to know what happens for indexed color mode and the Y* and A8 modes for the sake of thoroughness, but I doubt they're used w/ colorkeying in practice.

Comment (mborgerson) [reply hw/xbox/nv2a/pgraph/shaders.c]: If you do not plan to look into how the hardware handles these cases in this PR, then a comment indicating the open point for research would be great, thanks

File: hw/xbox/nv2a/pgraph/gl/shaders.c (hunk 2 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/gl/shaders.c]: Done

File: hw/xbox/nv2a/pgraph/shaders.c (hunk 6 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/shaders.c]: Done

File: hw/xbox/nv2a/pgraph/vk/shaders.c [hunk 7]
```diff
@@ -490,7 +496,21 @@ static void shader_update_constants(PGRAPHState *pg, ShaderBinding *binding,
...
+            pgraph_reg_r(pg, NV_PGRAPH_COLORKEYCOLOR2),
+            pgraph_reg_r(pg, NV_PGRAPH_COLORKEYCOLOR3),
+        };
+        uniform1uiv(&binding->fragment->uniforms, binding->color_key_loc, 4,
+                    color_key_colors);
+    }
+    if (binding->color_key_ignore_alpha_loc != -1) {
+        uniform1iv(&binding->fragment->uniforms,
+                   binding->color_key_ignore_alpha_loc, 4,
+                   (int32_t *)&state->psh.colorkey_ignore_alpha);
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/vk/shaders.c]: `colorkey_ignore_alpha` array element is `bool` type of size 1, but the glsl `colorKeyIgnoreAlpha` element is `int` type of size 4. This call to `uniform1iv` will overread the `colorkey_ignore_alpha` array and provide junk to the uniforms. Recommend creating an intermediate array like in the preceding lines

File: hw/xbox/nv2a/pgraph/glsl/psh.c [hunk 8]
```diff
@@ -174,6 +174,13 @@ enum PS_DOTMAPPING
     PS_DOTMAPPING_HILO_HEMISPHERE=     0x07L, // - * * *
 };
 
+enum PS_COLORKEYMODE {
+    COLOR_KEY_NONE = 0,
+    COLOR_KEY_KILL_ALPHA = 0x01,
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/glsl/psh.c]: nit: Unnecessary hex prefix

File: hw/xbox/nv2a/pgraph/glsl/psh.c [hunk 9]
```diff
@@ -731,6 +738,21 @@ static void apply_convolution_filter(const struct PixelShader *ps, MString *vars
...
 
+static void define_colorkey_comparator(MString *preflight)
+{
+    // clang-format off
+    mstring_append(
+        preflight,
+        "bool check_color_key(vec4 texel, uint color_key, bool ignore_alpha) {\n"
+        "    uvec4 components = uvec4(round(texel * 255.0));\n"
+        "    if (ignore_alpha) {\n"
+        "      return uint((components.r << 16) + (components.g << 8) + components.b) == (color_key & 0x00FFFFFFu);\n"
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/glsl/psh.c]: * `round` is implementation specific at 0.5. We probably want consistent behavior, so adding 0.5 will round to nearest
* Since we are masking color_key anyway, I think it makes sense to transform `ignore_alpha` here to a bitmask, which simplifies things a bit:

```glsl
bool check_color_key(vec4 texel, uint color_key, uint color_key_mask) {
    uvec4 c = uvec4(texel * 255.0 + 0.5);
    uint packed = (c.a << 24) | (c.r << 16) | (c.g << 8) | c.b;
    return (packed & color_key_mask) == (color_key & color_key_mask);
}
```

I suspect this will also come in handy when we investigate color keying on other texture formats.

File: hw/xbox/nv2a/pgraph/glsl/psh.c (hunk 8 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/glsl/psh.c]: Done

File: hw/xbox/nv2a/pgraph/glsl/psh.c (hunk 9 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/glsl/psh.c]: Makes sense, done.

File: hw/xbox/nv2a/pgraph/vk/shaders.c (hunk 7 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/vk/shaders.c]: Obviated by change to use (hopefully) future-proofed masks.

**Review by abaire — COMMENTED** [review]
Did a slightly more extensive cleanup based on your suggestion to use a generic mask instead of a flag for alpha ignore modes.

@mborgerson as an FYI, I'm away from my Linux machine for a while so the latest Vulkan changes haven't been tested

**Comment by mborgerson** [comment]
~~@Triticum0 would you mind testing the latest build in vulkan+gl for the aforementioned games~~ Tried it locally with test suite.

**Comment by mborgerson** [comment]
Thanks!

**Comment by Triticum0** [comment]
Fixed NBA Inside Drive 2004
Before 
xemu-2025-06-05-03-56-49
After
xemu-2025-06-30-01-36-41

**Comment by Triticum0** [comment]
@abaire I didn't test NBA Inside Drive 2004 properly seem to only be fixed on vulkan. opengl wasn't  fixed.

**Comment by abaire** [comment]
> @abaire I didn't test NBA Inside Drive 2004 properly seem to only be fixed on vulkan. opengl wasn't fixed.

Probably worth filing a new bug or reopening if there was a bug specific to that game. 

It seems weird that it would've been fixed on Vulkan but not OGL, maybe it wasn't actually broken on Vulkan before this PR and this change just had no effect for that game?
