### PR TITLE
nv2a: Enforce point params min/max size

### LINKED ISSUE #2378: Stolen : Rain squares bug - point param base scaling does not match HW
### Title

https://xemu.app/titles/48500001/#Stolen

### Bug Description

Seem the rain during first level causing these gray squares to appear on the floor and on player model

Image

https://github.com/user-attachments/assets/67f068a3-f164-4ad7-9571-b389d20dcec9

### Expected Behavior

Should not occur
https://youtu.be/oykDpOjq8dE?t=302

### xemu Version

0.8.96

### System Information

OS | Windows 10
CPU | AMD Ryzen 5 5700x Eight-Core Processoer
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 570.133.07
Render | Opengl

### Additional Context

Renderdoc:
https://drive.google.com/file/d/12HLd07sHHrbIbzQv4gQ3i24EwFsHCHi7/view?usp=sharing

Pgraph file:

[Stolen Ptrace.zip](https://github.com/user-attachments/files/22427031/Stolen.Ptrace.zip)

### PR DESCRIPTION
**Pull request by abaire**
[Tests](https://github.com/abaire/nxdk_pgraph_tests/blob/5920c89548e47675f28c7e347f07fc3ee54a4709/src/tests/point_sprite_tests.cpp#L27) 
[HW results](https://abaire.github.io/nxdk_pgraph_tests_golden_results/results/Point_sprite/index.html)

Fixes #2378

### CODE REVIEW

**Comment by abaire** [comment]
@Triticum0 can you verify that this fixes #2378 when you have some time? I don't own that title.

I'm also waiting on the full test suite to make sure this doesn't regress anything, but I think the lack of clamping was just an oversight.

**Comment by Triticum0** [comment]
Seems to fix the bug on my end on opengl and vulkan
xemu-2025-11-09-01-14-13

Previous report didn't mention it at the time as Handle point sprites, scaling wasn't implemented.

File: hw/xbox/nv2a/pgraph/glsl/vsh-ff.c [hunk 1]
```diff
@@ -489,13 +489,15 @@ GLSL_DEFINE(materialEmissionColor, GLSL_LTCTXA(NV_IGRAPH_XF_LTCTXA_CM_COL) ".xyz
...
     if (state->point_params_enable) {
         mstring_append(
             body,
             "  float d_e = length(position * modelViewMat0);\n"
+            "  float ptMinSize = min(pointParams[7], 63.875);\n"
+            "  float ptMaxSize = min(pointParams[3] + ptMinSize, 63.875);\n"
             "  oPts.x = 1/sqrt(pointParams[0] + pointParams[1] * d_e + pointParams[2] * d_e * d_e) + pointParams[6];\n");
-        mstring_append_fmt(body, "  oPts.x = min(oPts.x * pointParams[3] + pointParams[7], 64.0) * %d;\n",
+        mstring_append_fmt(body,
+                           "  oPts.x = max(min(oPts.x * pointParams[3] + pointParams[7], ptMaxSize), ptMinSize) * %d;\n",
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/glsl/vsh-ff.c]: A little cleaner to use `clamp` here

Comment (abaire) [reply hw/xbox/nv2a/pgraph/glsl/vsh-ff.c]: Good call, done.

**Comment by mborgerson** [comment]
Thanks!

**Comment by Triticum0** [comment]
Also fixes  UEFA Champions League 2004-2005 goal text box
0.8.117
xemu-2025-12-22-03-42-50

0.8.116
xemu-2025-12-22-04-43-10
