### PR TITLE
nv2a: Implement support for border textures

### LINKED ISSUE #851: Oddworld: Stranger's Wrath - Black/green splotches on characters
### Title

https://xemu.app/titles/4541006d/#Oddworld:-Stranger's-Wrath

Oddworld: Stranger's Wrath
EA-109 [4541006d]

### Bug Description

Characters don't look correct: they have black/green splotches depending on position/lighting.

Step to reproduce this issue:

1. Launch the game
2. Select New Game/Load any game
3. Admire the broken characters.

image

### Expected Behavior

Characters shouldn't look like that. Attaching the same screenshot of my previous reported issue, it works just fine to see how characters should be (no black splotches anywhere).

image

### xemu Version

v0.6.3

Never worked in any previous version.

### System Information

OS: Windows 10
CPU: Intel i9-9900k
GPU: Nvidia RTX 2080 Ti
GPU Driver: 512.15

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by abaire**
Fixes #851 

Partially addresses #1004. 3d bordered textures still don't match HW, but the HW results are also incorrect looking so I suspect there is some nuance to their function that I need to address in the test.
2D and 3D cubemaps should match hardware with this PR, `DOT_ST` and `DOT_STR_CUBE` should also match HW based on what I see from Oddworld

Linear bordered textures will also need to be tested and potentially fixed (I don't know of a game using them offhand and this is already a large change).

[Test](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/texture_cubemap_tests.cpp)
[HW results](https://github.com/abaire/nxdk_pgraph_tests_golden_results/wiki/Results-Texture_border)

Screenshot_20220602_160522

### CODE REVIEW

File: hw/xbox/nv2a/psh.c [hunk 1]
```diff
@@ -665,6 +665,21 @@ static void psh_append_shadowmap(const struct PixelShader *ps, int i, bool compa
 
 static MString* psh_convert(struct PixelShader *ps)
 {
+    // Adjust the s, t coordinates in the given VAR to account for the 4 texel
+    // border supported by the hardware.
+#define APPLY_BORDER_ADJUSTMENT(VAR)                                          \
```
Comment (mborgerson) [inline hw/xbox/nv2a/psh.c]: Can we make this a proper function

File: hw/xbox/nv2a/pgraph.c [hunk 2]
```diff
@@ -4388,12 +4388,40 @@ static void pgraph_bind_shaders(PGRAPHState *pg)
...
 
-        unsigned int color_format =
-            GET_MASK(pg->regs[NV_PGRAPH_TEXFMT0 + i*4],
-                     NV_PGRAPH_TEXFMT0_COLOR);
+        uint32_t tex_fmt = pg->regs[NV_PGRAPH_TEXFMT0 + i*4];
+        unsigned int color_format = GET_MASK(tex_fmt, NV_PGRAPH_TEXFMT0_COLOR);
         ColorFormatInfo f = kelvin_color_format_map[color_format];
         state.psh.rect_tex[i] = f.linear;
 
+        uint32_t border_source = GET_MASK(tex_fmt,
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph.c:4534]: Let's add a check for linear textures using texture borders so we can find out what games, if any, are affected by this

File: hw/xbox/nv2a/psh.c (hunk 1 above)
Comment (abaire) [reply hw/xbox/nv2a/psh.c]: Done.

File: hw/xbox/nv2a/pgraph.c (hunk 2 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph.c:4534]: Done.

**Comment by mborgerson** [comment]
Cool, thanks!
