### PR TITLE
nv2a: Gracefully ignore draws with no target bindings

### LINKED ISSUE #635: nv2a: color_binding || zeta_binding assertion failure
### Title

https://xemu.app/titles/5451001a/#Nickelodeon-SpongeBob-SquarePants-in-Battle-for-Bikini-Bottom
https://xemu.app/titles/4d570005/#Area-51
https://xemu.app/titles/5553001c/#Batman-Rise-of-Sin-Tzu
https://xemu.app/titles/5553004b/#Cold-Fear
https://xemu.app/titles/55530018/#Beyond-Good-Evil
### Bug Description

nv2a: color_binding || zeta_binding assertion failure from bubble moves.

### Expected Behavior
It shouldn't crash from bubble moves.

### xemu Version

v0.6.2-34-g62d04a3636
Was working in v.0.6.2-32-gd0fd0cb3e4

### System Information

OS: Windows 10
CPU: Intel(R) Xeon(R) CPU(TM) E5-2678 v3 @ 2.50GHz
GPU: NVIDIA Quadro P5000
GPU Driver: 462.96 NVIDIA

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by abaire**
Fixes #635 

[Test that triggers the assert without the fix](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/color_zeta_disable_tests.cpp)
[Tests of stencil behavior more generally](https://github.com/antangelo/nxdk_pgraph_tests/blob/stencil-tests/src/tests/stencil_tests.cpp)

### CODE REVIEW

**Comment by Triticum0** [comment]
Do you need me to test the games?

**Comment by mborgerson** [comment]
The assertion is there because I suspect we have missed something

**Comment by abaire** [comment]
We could leave the assert in and put it behind the check to see if any of color/depth/stencil are write enabled; that would catch erroneous states and still work in the case that the bindings aren't necessary.

I have a HW test written, waiting for an nvtrace to complete so I can make sure it really behaves the way I expect, @antangelo mentioned running into errors on HW when testing this case.

**Comment by abaire** [comment]
HW test fails in the same way that @antangelo encountered so there is something more interesting to this. I'll dig into it some more.

**Comment by abaire** [comment]
I spent some more time investigating Spongebob and am fairly confident that I figured out why they're not getting an exception where my test (and @antangelo's) are. Details in my latest comment in #635, I have a [test case pending](https://github.com/abaire/nxdk_pgraph_tests/commit/f0bb7440a2c3f00f51df4945b35d045e427d27dd#diff-ecc0768980ac93f98ca7a964016bb20e0bb1b96d0933608607bbbdf04bcf8096R49) but @antangelo wrote a much more thorough test that I'd rather see merged into the test repo.

I'll leave this in draft mode until my results are reproduced by @antangelo.

**Comment by antangelo** [comment]
[Test cases](https://github.com/antangelo/nxdk_pgraph_tests/blob/stencil-tests/src/tests/stencil_tests.cpp)

Results (on Xbox):
Stencil_REPLACE

with stencil test enabled:
Stencil_REPLACE_ST

Note that these tests are still not entirely accurate to hardware on xemu (see #724 for example, the behavior seems to have changed a bit since), but these issues are not related to this PR, so I can address them in a followup.

File: hw/xbox/nv2a/pgraph.c [hunk 1]
```diff
@@ -2833,6 +2840,18 @@ DEF_METHOD(NV097, SET_BEGIN_END)
         assert(parameter <= NV097_SET_BEGIN_END_OP_POLYGON);
 
         pgraph_update_surface(d, true, true, depth_test || stencil_test);
+
+        if (!(color_write || depth_test || stencil_test)) {
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph.c:2844]: ~~Should this test against zeta write mask (like color), not just whether the depth/stencil tests are enabled?~~ Nevermind, I think this should be okay. If test is disabled I believe writes will also be disabled like OpenGL spec (but it would be good to confirm).

Comment (antangelo) [reply hw/xbox/nv2a/pgraph.c:2844]: Did a quick search through the pgraph logs I have:
- BFBB has depth mask off and stencil mask on
- Cold Fear has both depth and stencil masks on
- Batman has both depth and stencil masks on

The stencil tests I wrote exercise this case with the depth mask off and stencil mask on.

For the stencil test I believe OpenGL spec is to assume the stencil test has passed if the mask is disabled (see https://www.khronos.org/opengl/wiki/Stencil_Test ), and the pass op is applied. The stencil tests seem to indicate this is not the case on Xbox-- instead disabling the stencil test will not apply the pass op to the zeta buffer.

Comment (abaire) [reply hw/xbox/nv2a/pgraph.c:2844]: For the depth test case I have previously confirmed that disabling the test disables writes on nv2a (it broke a test I was writing that had erroneously left the test disabled when explicitly enabling the mask).
