### PR TITLE
nv2a: Improve handling of SET_POINT_SIZE

### LINKED ISSUE #1913: Handling of NV097_SET_POINT_SIZE is incorrect with OpenGL renderer and incorrect for the programmable pipeline with Vulkan
### Bug Description

On Linux/Nvidia/OpenGL, point size seems to be ignored entirely: https://abaire.github.io/xemu-nxdk_pgraph_tests_results/compare/xemu-0.8.20-master-3bdb9e7fd4d6c9f5adec0543f1679d2943a0d092/Linux_x86_64/gl_NVIDIA_Corporation_NVIDIA_GeForce_GTX_1070-PCIe-SSE2%3Agslv_4.00_NVIDIA_via_Cg_compiler/Point_size.html

On Linux/Nvidia/Vulkan, point size is not handled correctly on the programmable pipeline: https://abaire.github.io/xemu-nxdk_pgraph_tests_results/compare/xemu-0.8.20-master-3bdb9e7fd4d6c9f5adec0543f1679d2943a0d092/Linux_x86_64/vk_NVIDIA_Corporation_NVIDIA_GeForce_GTX_1070-PCIe-SSE2%3Agslv_4.00_NVIDIA_via_Cg_compiler/Point_size.html

### Expected Behavior

https://abaire.github.io/nxdk_pgraph_tests_golden_results/results/Point_size/index.html

### xemu Version

xemu-0.8.20-master-3bdb9e7fd4d6c9f5adec0543f1679d2943a0d092

### System Information

xemu_version: 0.8.20
xemu_branch: master
xemu_commit: 3bdb9e7fd4d6c9f5adec0543f1679d2943a0d092
xemu_date: Sun Feb 16 00:00:03 UTC 2025
xemu_settings_get_base_path: base path: /mnt/linux_data/development/xbox/xemu-nxdk_pgraph_tests_results/cache/xemu-v0.8.20-x86_64.AppImage.home/.local/share/xemu/xemu/
xemu_settings_get_path: config path: /mnt/linux_data/development/xbox/xemu-nxdk_pgraph_tests_results/cache/xemu-v0.8.20-x86_64.AppImage.home/.local/share/xemu/xemu/xemu.toml
CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
OS_Version: Ubuntu 24.04.2 LTS
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: NVIDIA GeForce GTX 1070/PCIe/SSE2
GL_VERSION: 4.0.0 NVIDIA 570.86.15
GL_SHADING_LANGUAGE_VERSION: 4.00 NVIDIA via Cg compiler
Enabled instance extensions:
- VK_KHR_surface
- VK_KHR_xlib_surface
- VK_KHR_get_physical_device_properties2
- VK_KHR_external_semaphore_capabilities
- VK_KHR_external_memory_capabilities
Available physical devices:
- NVIDIA GeForce GTX 1070
- NVIDIA GeForce GTX 1070
- llvmpipe (LLVM 19.1.1, 256 bits)
Selected physical device: NVIDIA GeForce GTX 1070
- Vendor: 10de, Device: 1b81
- Driver Version: 570.344.960
Enabled device extensions:
- VK_KHR_external_semaphore
- VK_KHR_external_memory
- VK_KHR_external_memory_fd
- VK_KHR_external_semaphore_fd
- VK_EXT_custom_border_color
- VK_EXT_provoking_vertex
- VK_EXT_memory_budget

### Additional Context

_No response_

### LINKED ISSUE #2093: Fatal Frame: Camera blue ring missing
### Title

https://xemu.app/titles/54430004/#Fatal-Frame

TC-004

### Bug Description

Camera works for everything, but environmental objects no Blue ring over said objects.

Image

### Expected Behavior

Camera should light up with a blue ring when over the objects in the picture

Image

### xemu Version

v0.8.47

### System Information

OS: Windows 11
GPU: GTX 1070 TI
CPU: Ryzen 5 2600X
Xemu Version: V0.8.47

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by abaire**
Improves the handling of NV097_SET_POINT_SIZE:

1) Point sizes > 0x1FF are now properly ignored, matching HW behavior. 
2) Programmable pipeline oPts is now bound to `NV097_SET_POINT_PARAMS_ENABLE` in order to match HW behavior.

This does not attempt to address cases where the host GL does not support point sizes up to ~64 pixels, nor does it investigate behavior at renderscale > 1x.

[Tests](https://github.com/abaire/nxdk_pgraph_tests/blob/49b299499e54a1492a4f82356863a4ab08b02b08/src/tests/point_size_tests.cpp#L127)

[HW results](https://abaire.github.io/nxdk_pgraph_tests_golden_results/results/Point_size/index.html) 

[Hw results 2](https://abaire.github.io/nxdk_pgraph_tests_golden_results/results/Point_params/index.html)

[PR results](https://abaire.github.io/xemu-dev_pgraph_test_results/fix_1913_handle_point_size/index.html) - note that there is a stale first result and there are still some minor differences in rounding.

Fixes #1913
Fixes #2093

### CODE REVIEW

**Comment by abaire** [comment]
Possibly fixes #2093. Would be great if somebody could check on 1x and higher.

**Comment by GiladN1** [comment]
I tested this on Windows 11 and RTX 3080, can confirms it fixes Fatal Frame 1's camera aiming on both OpenGL and Vulkan. I tested both 1x and 4x native resolutions and both worked without issues.

**Comment by Triticum0** [comment]
I tested it as well and definitely fixed

**Comment by Triticum0** [comment]
Tested #2378 as thought it might be related, it not.

File: hw/xbox/nv2a/pgraph/pgraph.c [hunk 1]
```diff
@@ -1729,7 +1729,11 @@ DEF_METHOD_INC(NV097, SET_TEXTURE_MATRIX_ENABLE)
 
 DEF_METHOD(NV097, SET_POINT_SIZE)
 {
-    PG_SET_MASK(NV_PGRAPH_POINTSIZE, NV097_SET_POINT_SIZE_V, parameter);
+    if (parameter > 0x1FF) {
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/pgraph.c]: Prefer to keep the constant definition and use it here instead of hardcoding this raw value here

Comment (abaire) [reply hw/xbox/nv2a/pgraph/pgraph.c]: Can we rename the constant to something like `NV_PGRAPH_POINTSIZE_V_MAX`? 

My concern is that generally those constants are bitmasks whereas this is an actual maximum. Naming it with the bitmask convention invites confusion / "fixes" back to the original, "correct looking without checking specific tests", code.

Comment (abaire) [reply hw/xbox/nv2a/pgraph/pgraph.c]: Looked at more values, I think adding anything after the `_V` suffix would make it clearer that this isn't a bitmask despite looking like one. It'll match the convention of `NV097_SET_SHADE_MODE_V_FLAT` etc...

File: hw/xbox/nv2a/pgraph/glsl/vsh.c [hunk 2]
```diff
@@ -306,6 +304,12 @@ MString *pgraph_glsl_gen_vsh(const VshState *state, GenVshGlslOptions opts)
         pgraph_glsl_gen_vsh_prog(
             VSH_VERSION_XVS, (uint32_t *)state->programmable.program_data,
             state->programmable.program_length, header, body);
+        if (!state->point_params_enable) {
+            mstring_append_fmt(body, "  oPts.x = %f * %d;\n",
+                               state->point_size <= 0.f ? 1.f :
```
Comment (mborgerson) [inline hw/xbox/nv2a/pgraph/glsl/vsh.c:309]: For FF there's a lower bound of 1.0, but here any value >0.0 is permitted? Did you mean to clamp to 1.0 here as above?

File: hw/xbox/nv2a/pgraph/pgraph.c (hunk 1 above)
Comment (mborgerson) [reply hw/xbox/nv2a/pgraph/pgraph.c]: Works for me!

File: hw/xbox/nv2a/pgraph/glsl/vsh.c (hunk 2 above)
Comment (abaire) [reply hw/xbox/nv2a/pgraph/glsl/vsh.c:309]: No, it's intentional. See https://abaire.github.io/nxdk_pgraph_tests_golden_results/results/Point_size/index.html

FF
ff

Programmable
programmable

Comment (mborgerson) [reply hw/xbox/nv2a/pgraph/glsl/vsh.c:309]: Interesting... The FF set appear thicker overall when swapping between the two images. I'll need to take a look at the test code and the actual number of pixels rendered. Based on this, it looks like 0 is clamped to 1, and 1/8-7/8 are rounded down to 0. I think gl/vk rasterizers will actually clamp values in [0,1] to 1.0 when rendering, which appears to be the case in your linked xemu test results.

Comment (abaire) [reply hw/xbox/nv2a/pgraph/glsl/vsh.c:309]: Yeah, it is odd behavior. It may be that perfect emulation would require rendering points in a shader instead of relying on the GL.

It's also possible that D3D would not have allowed these values and would've clamped like modern GL/VK in which case it might be moot for typical users.

Comment (mborgerson) [reply hw/xbox/nv2a/pgraph/glsl/vsh.c:309]: For the case when no fragments should be rendered (apparently when 0<pointSize<1), we should be able to just `discard` fragments in the fragment shader. Anyway, happy to accept this improvement as it is and iterate

**Comment by mborgerson** [comment]
Thanks!
